### ISSUE TITLE
aslanbek - 3 days is too large for feed's staleness check

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-midas-judging#1]
aslanbek

medium

# 3 days is too large for feed's staleness check

## Vulnerability Detail

On Mainnet, EUR/USD feed has a heartbeat of 1 day; on Arbitrum - 1 hour. 
https://data.chain.link/feeds/ethereum/mainnet/eur-usd
https://data.chain.link/feeds/arbitrum/mainnet/eur-usd

However, `DataFeed#getDataInBase18` reverts only if the price has not been updated for more than 3 days.

## Impact

If a feed becomes stale, `DepositVault#minAmountToDepositInUsd`, instead of reverting, will return a stale price.

a) First deposits with real value >= 100_000 EUR may revert if feed's price is higher than the actual price;
b) First deposits with real value < 100_000 EUR could be accepted if feed's price is lower than the actual price.

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/a4a3cc23bb891913ce44665a4cdea9f5c1190f6c/midas-contracts/contracts/feeds/DataFeed.sol#L27

https://github.com/sherlock-audit/2024-05-midas/blob/a4a3cc23bb891913ce44665a4cdea9f5c1190f6c/midas-contracts/contracts/feeds/DataFeed.sol#L64-L77

## Tool used

Manual Review

## Recommendation

Instead of `3 days`, use `3600 seconds` for Arbitrum and `86400 seconds` for Ethereum mainnet.

Duplicate of #110

**Comment by WangSecurity** [comment]
This report will be invalidated based on the escalation on #110.
