### ISSUE TITLE
pkqs90 - `M_TBILL_BURN_OPERATOR_ROLE` cannot burn `mTBILL` tokens from users who are blacklisted.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-midas-judging#107]
pkqs90

medium

# `M_TBILL_BURN_OPERATOR_ROLE` cannot burn `mTBILL` tokens from users who are blacklisted.

## Summary

`M_TBILL_BURN_OPERATOR_ROLE` cannot burn `mTBILL` tokens from users who are blacklisted.

## Vulnerability Detail

The `burn()` function of `mTBILL` is called by the `M_TBILL_BURN_OPERATOR_ROLE` role, it should be able to burn tokens from any user. Quote the protocol team: *burning is our way to seize assets if necessary.*

However, since `_beforeTokenTransfer` is also called during the internal `_burn()` function, users that are blacklisted would not be able to be burned.

https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/mTBILL.sol#L90-L102
```solidity
    function burn(address from, uint256 amount)
        external
        onlyRole(M_TBILL_BURN_OPERATOR_ROLE, msg.sender)
    {
        _burn(from, amount);
    }

    ...

    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 amount
    )
        internal
        virtual
        override(ERC20PausableUpgradeable)
        onlyNotBlacklisted(from)
        onlyNotBlacklisted(to)
    {
        ERC20PausableUpgradeable._beforeTokenTransfer(from, to, amount);
    }
```

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.9.0/contracts/token/ERC20/ERC20Upgradeable.sol#L282-L298
```solidity
    function _burn(address account, uint256 amount) internal virtual {
        require(account != address(0), "ERC20: burn from the zero address");

>       _beforeTokenTransfer(account, address(0), amount);

        uint256 accountBalance = _balances[account];
        require(accountBalance >= amount, "ERC20: burn amount exceeds balance");
        unchecked {
            _balances[account] = accountBalance - amount;
            // Overflow not possible: amount <= accountBalance <= totalSupply.
            _totalSupply -= amount;
        }

        emit Transfer(account, address(0), amount);

        _afterTokenTransfer(account, address(0), amount);
    }
```

## Impact

`M_TBILL_BURN_OPERATOR_ROLE` cannot burn `mTBILL` tokens from users who are blacklisted.

## Code Snippet

- https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/mTBILL.sol#L90-L102
- https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.9.0/contracts/token/ERC20/ERC20Upgradeable.sol#L282-L298

## Tool used

Manual review

## Recommendation

Add a manual check if `to` address is 0, skip the blacklist check for `from` address.

**Comment by nevillehuang** [comment]
Escalate, I believe this issue is at best low severity, but will respect the decision of HOJ due to 2 reasons

1. Even if assets are not burnt, it will not impact the NAV of mTBILLs, and the user will never be able to utilize this funds anyways which fulfills the role of blacklisting
2. Admins can batch calls to unblacklist and burn within the same transaction.

**Comment by sherlock-admin3** [comment]
> Escalate, I believe this issue is at best low severity, but will respect the decision of HOJ due to 2 reasons
> 
> 1. Even if assets are not burnt, it will not impact the NAV of mTBILLs, and the user will never be able to utilize this funds anyways which fulfills the role of blacklisting
> 2. Admins can batch calls to unblacklist and burn within the same transaction.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by blutorque** [comment]
Escalate 

Should remain valid medium,
See issue #77 on how it affects the price economics of mTBill and why it's required to burn excess mTBill from circulation, also the behaviour is confirmed by sponser as well, 

![Screenshot 2024-05-30 211612](https://github.com/sherlock-audit/2024-05-midas-judging/assets/127722297/b72b3e56-6999-44cc-ae73-59a42e9677b7)

**Comment by sherlock-admin3** [comment]
> Escalate 
> 
> Should remain valid medium,
> See issue #77 on how it affects the price economics of mTBill and why it's required to burn excess mTBill from circulation, also the behaviour is confirmed by sponser as well, 
> 
> ![Screenshot 2024-05-30 211612](https://github.com/sherlock-audit/2024-05-midas-judging/assets/127722297/b72b3e56-6999-44cc-ae73-59a42e9677b7)
> 

You've deleted an escalation for this issue.

**Comment by blutorque** [comment]
Should remain valid medium,
See issue https://github.com/sherlock-audit/2024-05-midas-judging/issues/77 on how it affects the price economics of mTBill and why it's required to burn excess mTBill from circulation, also the behaviour is confirmed by sponser as well, check above.

**Comment by CarlosAlegreUr** [comment]
> Escalate, I believe this issue is at best low severity, but will respect the decision of HOJ due to 2 reasons
> 
> 1. Even if assets are not burnt, it will not impact the NAV of mTBILLs, and the user will never be able to utilize this funds anyways which fulfills the role of blacklisting
> 2. Admins can batch calls to unblacklist and burn within the same transaction.

I would like to add that I thought of this and did not send this issue for the reasons explained by @nevillehuang . And for an extra reason, the impact mentioned on issue #77 is false. It does not affect the tokenomics, even when blacklisting people from TBILL the price will still be pegged, as the blacklisted address wont be able to move their tokens anywhere, thus not even claiming. So in theory yeah those tokens exist but in practice they are unclaimable so it does not matter if there are or not assets in the real world backing them up. Plus what @nevillehuang said, the team can always safely burn them in a batch call.

Thus I do consider this issue and similar ones like #77 invalid, as they have no real consequence to the token or peg.

**Comment by CarlosAlegreUr** [comment]
> Should remain valid medium, See issue #77 on how it affects the price economics of mTBill and why it's required to burn excess mTBill from circulation, also the behaviour is confirmed by sponser as well, check above.

I think your conclusions are wrong. It does not really affect the price economics of MTBILL as the tokens are effectively frozen and thus they are not required to be backed-up by anything because **no-one will ever claim them**, also as @nevillehuang said the protocol can safely burn then though a batch call. All mentioned in more detail in my previous comment [above](https://github.com/sherlock-audit/2024-05-midas-judging/issues/107#issuecomment-2155891413)

**Comment by MxAxM** [comment]
> Escalate, I believe this issue is at best low severity, but will respect the decision of HOJ due to 2 reasons
> 
>     1. Even if assets are not burnt, it will not impact the NAV of mTBILLs, and the user will never be able to utilize this funds anyways which fulfills the role of blacklisting
> 
>     2. Admins can batch calls to unblacklist and burn within the same transaction.

We consider burner and blacklisting two different roles so it's not possible to call unblacklist and burn in same transaction, also it's clearly mentioned that burner should be able to burn tokens but this issue prevents it, this can affect off-chain calculations

**Comment by vararg** [comment]
@MxAxM by this logic preventing mint is also an issue?

1. In the contest description it's clearly said that BLACKLISTED address can't interact with the contract. 

Burn and mint are still an interactions between address and contract.

In result description of Minter and Burner roles just stayed against Blacklist role description. 

> M_TBILL_MINT_OPERATOR_ROLE | Minting token(s) upon issuance | TRUSTED
> M_TBILL_BURN_OPERATOR_ROLE | Burning token(s) upon redemption | TRUSTED

> BLACKLISTED_ROLE | Cannot access the mTBILL contract | RESTRICTED
> These roles (Greenlist, Blacklist) have limited rights. Greenlisted addresses can interact with the contract and blacklisted cannot - we can assume that neither role can act maliciously. 

2. I also can argue against expectation that auditor easily can do such assumptions. By rules on Sherlock we shouldn't just report random things that we are not sure(and we will have bad ratio). And we see only small piece of the contract where huge part of business logic are offchain. How auditor should understand from description above that BURN of Blacklisted role can't affect anything out of the scope of existing system?

**Comment by blutorque** [comment]
> by this logic preventing mint is also an issue?
 
No, why does even admin want to mint mTBill to a blacklisted user!. Its same as saying, why admin aren't printing money to a blacklist address. 
I agree, there was not enough context and most of protocol logic is off-chain. But I still think this as an issue, otherwise, wth we are supposed to do with `burn`. Anyway, I'll go with what HOJ decides.

**Comment by vararg** [comment]
> > by this logic preventing mint is also an issue?
> 
> No, why does even admin want to mint mTBill to a blacklisted user!. Its same as saying, why admin aren't printing money to a blacklist address. I agree, there was not enough context and most of protocol logic is off-chain. But I still think this as an issue, otherwise, wth we are supposed to do with `burn`. Anyway, I'll go with what HOJ decides.

And what about point how doc said that contract should not interact with the blacklisted address?

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/RedDuck-Software/midas-contracts/pull/44

**Comment by WangSecurity** [comment]
As I see in the README, the `M_TBILL_BURN_OPERATOR_ROLE` only burns tokens upon redemption and blacklisted role cannot redeem. Hence, from my perspective, it works as it should, the blacklsited address cannot redeem, therefore, the burn role won't burn their tokens cause they only expected to burn tokens upon redemption.

Secondly, it doesn't effect the mTBILL token and its peg to IB01. Thirdly, I see the message from the sponsor, but as explained above, the protocol works as expected based on README. 

Please correct me if I misunderstood the README, but planning to accept the escalation and invalidate the issue.

**Comment by blutorque** [comment]
> therefore, the burn role won't burn their tokens cause they only expected to burn tokens upon redemption.

Have convo with sponser,  they see it as a nice to have a feature😅, should be invalid

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [nevillehuang](https://github.com/sherlock-audit/2024-05-midas-judging/issues/107/#issuecomment-2155455595): accepted

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
