### ISSUE TITLE
Naresh - `Chainlink` oracle returns stale price due to `_HEALTHY_DIFF` variable in `DataFeed` being set to 3 days

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-midas-judging#11]
Naresh

medium

# `Chainlink` oracle returns stale price due to `_HEALTHY_DIFF` variable in `DataFeed` being set to 3 days

## Summary

The `DataFeed` contract utilizes a `_HEALTHY_DIFF` constant set to `3 days`. This duration is longer than the `Chainlink` heartbeat, which is `3600` seconds (1 hour), potentially introducing a significant delay in recognizing stale or outdated price data.

## Vulnerability Detail

The `DataFeed::_getDataInBase18()` function checks if the difference between the `block.timestamp - updatedAt <= _HEALTHY_DIFF`. 
```solidity
  function _getDataInBase18()
        private
        view
        returns (uint80 roundId, uint256 answer)
    {
        uint8 decimals = aggregator.decimals();
        (uint80 _roundId, int256 _answer, , uint256 updatedAt, ) = aggregator
            .latestRoundData();
        require(_answer > 0, "DF: feed is deprecated");
        require(
            // solhint-disable-next-line not-rely-on-time
            block.timestamp - updatedAt <= _HEALTHY_DIFF,
            "DF: feed is unhealthy"
        );
        roundId = _roundId;
        answer = uint256(_answer).convertToBase18(decimals);
    }
```
The `_HEALTHY_DIFF` is defined to be 3 days.
```solidity
 uint256 private constant _HEALTHY_DIFF = 3 days;
```

## Impact

The `Chainlink` heartbeat indicates the expected frequency of updates from the oracle. The `Chainlink` heartbeat on Ethereum for `Eth/Usd` is `3600` seconds (1 hour).
https://docs.chain.link/data-feeds/price-feeds/addresses?network=ethereum&page=1&search=0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419

But the defined `_HEALTHY_DIFF ` in the `DataFeed` is 3 days.

A `_HEALTHY_DIFF` that is significantly longer than the heartbeat can lead to scenarios where the `DataFeed` contract accepts data that may no longer reflect current market conditions. Also, in volatile markets, a `3 days` window leads to accepting outdated prices, increasing the risk of price slippage.

## Code Snippet

https://github.com/sherlock-audit/2024-05-midas/blob/a4a3cc23bb891913ce44665a4cdea9f5c1190f6c/midas-contracts/contracts/feeds/DataFeed.sol#L27

https://github.com/sherlock-audit/2024-05-midas/blob/a4a3cc23bb891913ce44665a4cdea9f5c1190f6c/midas-contracts/contracts/feeds/DataFeed.sol#L64-L80

## Tool used

Manual Review

## Recommendation

Consider reducing the `_HEALTHY_DIFF` to align more closely with the `Chainlink` heartbeat on Ethereum, enhancing the relevance of the price data.

Duplicate of #110

**Comment by WangSecurity** [comment]
This report will be invalidated based on the escalation on #110.
