### ISSUE TITLE
h2134 - Staleness checking larger than price feeds heartbeat intervals may lead to stale or incorrect prices

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-midas-judging#111]
h2134

medium

# Staleness checking larger than price feeds heartbeat intervals may lead to stale or incorrect prices

## Summary
Staleness checking in **DataFeed** is set to `3 days`, which is much larger than price feeds heartbeat intervals, this may lead to stale or incorrect prices.

## Vulnerability Detail
Contract **DataFeed** is used as a wrapper of ChainLink`s AggregatorV3 data feeds to fetch [EUR/USD](https://data.chain.link/ethereum/mainnet/fiat/eur-usd) (in the current implementation) and [IB01/USD](https://data.chain.link/ethereum/mainnet/indexes/ib01-usd) (in the near future) prices.

Protocol assumes the price is only stale if more than three days have passed, so the staleness checking variable [_HEALTHY_DIFF](https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L27) is set to **3 days**:
```solidity
    uint256 private constant _HEALTHY_DIFF = 3 days;
```
In fact, both `EUR/USD` and `IBO1/USD`'s heartbeat intervals are `1 days`.

[EUR](https://docs.chain.link/data-feeds/price-feeds/addresses/?network=ethereum&page=1&search=EUR):
<img src="https://i.ibb.co/7zNm777/EUR.png" alt="EUR" border="0">

[IB01](https://docs.chain.link/data-feeds/price-feeds/addresses/?network=ethereum&page=1&search=IB01):
<img src="https://i.ibb.co/JnXbCdh/IBO1.png" alt="IBO1" border="0">

This means if the price feeds perform normally and the price data values stay within the deviation parameters, the price feeds will update the price every 1 day, even when it is not standard market hour.

This can be verified by query `getRoundData()` from [EUR price feed contract](https://etherscan.io/address/0xb49f677943BC038e9857d61E7d053CaA2C1734C1#readContract).

Updated at **GMT: Saturday, May 25, 2024 10:38:47 AM** (1716633527)
>roundId :  73786976294838214036
answer :  108468000
startedAt :  1716633527
updatedAt :  **1716633527**
answeredInRound :  73786976294838214036

Updated at **GMT: Sunday, May 26, 2024 10:39:11 AM** (1716719951)
>roundId :  73786976294838214037
answer :  108468000
startedAt :  1716719951
updatedAt :  **1716719951**
answeredInRound :  73786976294838214037

This also means if the difference between `block.timestamp` and `updatedAt` timestamps is much larger than the heartbeat intervals, let's say 2 days, it's highly possible that the price feeds are not running properly, the price data can be stale or incorrect, however, such price data can be accepted and returned by **DataFeed** since **_HEALTHY_DIFF** is `3 days`.

## Impact
Improper staleness checking may result in stale or incorrect prices returned by **DataFeed**.
1. `EUR/USD` is used to denominate the minimal deposit amount in EUR, thus uses are required need to deposit much less/more funds than expected for the first deposit;
2. `IBO1/USD` is used to calculate the USD/mTBILL exchange price, the impact can be much more critical when the price feed is utilized in the protocol.

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L27

## Tool used
Manual Review

## Recommendation
Set `_HEALTHY_DIFF` slightly larger than the heartbeat interval.
```diff
-   uint256 private constant _HEALTHY_DIFF = 3 days;
+   uint256 private constant _HEALTHY_DIFF = 1 days + 1 hours;
```

Duplicate of #110

**Comment by WangSecurity** [comment]
This report will be invalidated based on the escalation on #110.
