### ISSUE TITLE
14si2o_Flint - Incorrect understanding of Chainlink heartbeat can lead to stale prices

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-midas-judging#116]
14si2o_Flint

medium

# Incorrect understanding of Chainlink heartbeat can lead to stale prices

## Summary

The IB01/USD Chainlink Datafeed has a heartbeat of 24 hours, meaning it will be updated every day regardless of market hours, contrary to what the protocol seems to believe. 

Using 3 days as a staleness threshold will lead to stale prices and a financial loss for the users.  

## Vulnerability Detail

The protocol has implemented a staleness threshold of three days based this statement from the readme: 

> IB01/USD Price from Chainlink is `RESTRICTED`, as their documentation states that the price will only be updated during defined market hours (weekends and holidays excluded), so we assume the price is only stale if more than three days have passed.

However, this is incorrect. The Datafeed, as can be seen on the Chainlink website (https://data.chain.link/feeds/ethereum/mainnet/ib01-usd), has a heartbeat of 24 hours and is updated every single day. Since the markets are closed during the weekend, the updated price of Saturday and Sunday does not change from the price of Friday, but the actual price has no relation to the freshness of data. 

## Impact

Allowing a staleness threshold of 3 days for a datafeed with a 24 hour heartbeat can lead to stale prices and significant financial losses for clients.  

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L27
## Tool used

Manual Review

## Recommendation

Change the `_HEALTHY_DIFF` to be 24 hours, the same as the heartbeat of the datafeed in question. 

Duplicate of #110

**Comment by WangSecurity** [comment]
This report will be invalidated based on the escalation on #110.
