### ISSUE TITLE
tpiliposian - Potential Risk Due to Fixed Healthy Difference in DataFeed Contract

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-midas-judging#14]
tpiliposian

medium

# Potential Risk Due to Fixed Healthy Difference in DataFeed Contract

## Summary

The `_HEALTHY_DIFF` constant in the `DataFeed.sol` contract is set to 3 days, which is used to validate the freshness of the exchange rate data from the Chainlink aggregator. During periods of high market volatility, a 3-day-old exchange rate may not accurately reflect the current market conditions, leading to potential inaccuracies in the minimum deposit amount calculations.

## Vulnerability Detail

The `minAmountToDepositInUsd()` function calculates the minimum deposit amount in USD by fetching the EUR/USD exchange rate:
```solidity
    function minAmountToDepositInUsd() public view returns (uint256) {
        return
            (minAmountToDepositInEuro * eurUsdDataFeed.getDataInBase18()) /
            10**18;
    }
```
The exchange rate is fetched from a Chainlink aggregator via the `getDataInBase18()` function, which ensures the returned data is no older than `_HEALTHY_DIFF` (3 days):
```solidity
        require(
            // solhint-disable-next-line not-rely-on-time
            block.timestamp - updatedAt <= _HEALTHY_DIFF,
            "DF: feed is unhealthy"
        );
```

## Impact

During periods of high market volatility, a 3-day-old exchange rate may not reflect the current market conditions accurately. This could lead to under- or overestimating the minimum deposit amount in USD.
Since `_HEALTHY_DIFF` is a constant, it cannot be adjusted dynamically to reflect changing market conditions:
```solidity
    uint256 private constant _HEALTHY_DIFF = 3 days;
```

## Code Snippet

https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/DepositVault.sol#L137-L141

https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L27

https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L54-L80

## Tool used

Manual Review

## Recommendation

Introduce a setter function that allows the contract owner or an authorized role to update the `_HEALTHY_DIFF` value, which will ensure the data's freshness is appropriate for the current environment and market volatility.

Duplicate of #110

**Comment by WangSecurity** [comment]
This report will be invalidated based on the escalation on #110.
