### ISSUE TITLE
0xhacksmithh - DataFeed will use the wrong price if the Chainlink aggregator returns price outside min/max range

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-midas-judging#142]
0xhacksmithh

medium

# DataFeed will use the wrong price if the Chainlink aggregator returns price outside min/max range

## Summary
Chainlink aggregators have a built in circuit breaker if the price of an asset goes outside of a predetermined price band. The result is that if an asset experiences a huge drop in value (i.e. LUNA crash) the price of the oracle will continue to return the minPrice instead of the actual price of the asset. 

Here is an real world example of above senario :: [Venus on BSC when LUNA imploded](https://rekt.news/venus-blizz-rekt/)
## Vulnerability Detail
Note that there is only checks for `price` to be non-zero and Healthyness check (which has its own problem explained [here](https://github.com/sherlock-audit/2024-05-midas-0xhacksmithh/issues/3)), but not within an acceptable range.

A similar issue is mentioned [here](https://github.com/sherlock-audit/2023-02-blueberry-judging/issues/18) and [here](https://solodit.xyz/issues/m-2-priceoracle-will-use-the-wrong-price-if-the-chainlink-registry-returns-price-outside-minmax-range-sherlock-none-iron-bank-git)
```solidity
    function _getDataInBase18()
        private
        view
        returns (uint80 roundId, uint256 answer)
    {
        uint8 decimals = aggregator.decimals();
        (uint80 _roundId, int256 _answer, , uint256 updatedAt, ) = aggregator
            .latestRoundData();
        require(_answer > 0, "DF: feed is deprecated");
        require(
            // solhint-disable-next-line not-rely-on-time
            block.timestamp - updatedAt <= _HEALTHY_DIFF,
            "DF: feed is unhealthy"
        );
        roundId = _roundId;
        answer = uint256(_answer).convertToBase18(decimals);
    }
```

## Impact
The wrong price may be returned in the event of a market crash.

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L64-L80

## Tool used

Manual Review

## Recommendation
```diff
        (uint80 _roundId, int256 _answer, , uint256 updatedAt, ) = aggregator
            .latestRoundData();
        require(_answer > 0, "DF: feed is deprecated");
        require(
            // solhint-disable-next-line not-rely-on-time
            block.timestamp - updatedAt <= _HEALTHY_DIFF,
            "DF: feed is unhealthy"
        );
+          require(price >= minPrice && price <= maxPrice, "invalid price"); // @audit use the proper minPrice and maxPrice for asset
        roundId = _roundId;
        answer = uint256(_answer).convertToBase18(decimals);
    }
```

**Comment by 0xhacksmithh** [comment]
I don't understand why this is invalid. it's classic bug found in some previous audits and there in report i mentioned and provide links to those Bug report.

**Comment by pronobis4** [comment]
Because everything is validated off-chain, the severity should be low.
