### ISSUE TITLE
0xhacksmithh - HEARTBEAT_TIME gap(`_HEALTHY_DIFF`) is too huge

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-midas-judging#146]
0xhacksmithh

medium

# HEARTBEAT_TIME gap(`_HEALTHY_DIFF`) is too huge

## Summary
_HEALTHY_DIFF = 3 days could not be safe. The oracle data still be stale one.

## Vulnerability Detail
oracle is using the HEARTBEAT_TIME as 3 Days. Since the price of oracle could vary in the time gap of 24 hours [Feed](https://data.chain.link/feeds/ethereum/mainnet/ib01-usd), using 3 Days could be dangerous.

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L27

https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L75

## Tool used

Manual Review

## Recommendation
Use 24 hours as hearbeat. [Feed](https://data.chain.link/feeds/ethereum/mainnet/ib01-usd)

Duplicate of #110

**Comment by WangSecurity** [comment]
This report will be invalidated based on the escalation on #110.
