### ISSUE TITLE
Audinarey - depositors can make deposits at less than the `minAmountToDepositInUsd()` and recieve more `mTBill`

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-midas-judging#156]
Audinarey

high

# depositors can make deposits at less than the `minAmountToDepositInUsd()` and recieve more `mTBill`

## Summary

As per the Audit documentation,
> IB01/USD Price from Chainlink is **RESTRICTED**, as their documentation states that the price will only be updated during defined market hours (weekends and holidays excluded), so we assume the price is only stale **if more than three days have passed**.

Network outages and large reorgs happen with relative frequency on L2 rollups. For instance, Arbitrum suffered 
- an hour-long outage just on (Dec.16 2023, 5PM GMT) ([source](https://github.com/ArbitrumFoundation/docs/blob/50ee88b406e6e5f3866b32d147d05a6adb0ab50e/postmortems/15_Dec_2023.md)).
- a 7 hour hour [downtime](https://x.com/arbitrum/status/1480165924355330051?s=20)
- and another 1 hour [downtime](https://x.com/arbitrum/status/1735699786618020205?s=20)

The protocols Chainlink implementation only checks that the price was updated in the last 3 days. However, there is no check for sequencer uptime meaning the sequencer could have been down within that time and stale prices reported in between causing users to deposit less than the required USD amount to receive more `mTBill`.

I am reporting this as a high because there is a possible leak of value from the protocol as shown below

## Vulnerability Detail
Assume the set `minAmountToDepositInEuro` is €100,000
- say at t = 0 chainlink price was updated
- at t = 6hr, the current price of the price of EUR/USD is 1.04  then `minAmountToDepositInUsd()` will be $104,000, then Alice a green listed user who is not free form minimum deposit must deposit a minimum of $104,000 for their deposit to be successful and receive say 100,000 `mTBill`.
- the price is checked to ensure that it has been updated within the last 3 days (72 hrs)
- at t = 64 hrs the Arbitrum sequencer goes down/suffers an outage and the last updated price is of EUR/USD is now 1.04 however the price has increased in the last 12hrs to 1.09, 
- Bob  a green listed user who is not free form minimum deposit is suppose to deposit a minimum of $109,000 which is the current equivalent of the `minAmountToDepositInEuro` but because the price of USD/EUR is stale and stuck at 1.04 he will still be able to deposit the $104,000 which less than the actual `minAmountToDepositInUsd()` and receives 100,000 `mTBill` leading to a leak of value since the depositor is getting more `mTBill` for less.
    - that is Bob get `mTBill` worth $109,000 by depositing $104,000
- All these happened without notice within 3 days.
- at t = 72 hrs the price is updated and the price of EUR/USD is now 1.09

## Impact
A first time depositor can can successfully deposit less than the `minAmountToDepositInUsd()` and receive `mTBill` equivalent to a stale EUR amount without reverting.

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/DepositVault.sol#L161

https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/DepositVault.sol#L103-L105

https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L64-L81

## Tool used

Manual Review

## Recommendation
- To mitigate this issue, consider integrating an external uptime feed such as [Chainlink's L2 Sequencer Feeds](https://docs.chain.link/data-feeds/l2-sequencer-feeds).
- IN addition, when the rollup is down, consider setting a minimum threshold constant for USD/EUR to multiply with `minAmountToDepositInEuro` to ensure the protocol still has control of the minimum amount users can deposit

Duplicate of #110

**Comment by WangSecurity** [comment]
This report will be invalidated based on the escalation on #110.
