### ISSUE TITLE
MohammedRizwan - Chainlink oracle returns stale price due to incorrect `_HEALTHY_DIFF` variable which is hardcoded to `3 days` causing losses in normal/volatile markets

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-midas-judging#158]
MohammedRizwan

medium

# Chainlink oracle returns stale price due to incorrect `_HEALTHY_DIFF` variable which is hardcoded to `3 days` causing losses in normal/volatile markets

## Summary
Chainlink oracle returns stale price due to incorrect `_HEALTHY_DIFF` variable which is hardcoded to `3 days` causing losses in normal/volatile markets

## Vulnerability Detail
`Midas` contracts will be deployed on Ethereum mainnet. `DataFeed.sol` contract fetches the asset prices from chainlink which is particularly used to fetch Euro/USD prices from chainlink when the user deposits the USD via [DepositVault.deposit()](https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/DepositVault.sol#L104) function.

```solidity
    function minAmountToDepositInUsd() public view returns (uint256) {
        return
            (minAmountToDepositInEuro * eurUsdDataFeed.getDataInBase18()) /
            10**18;
    }
```

On Ethereum mainnet, the EUR/USD price feed has an address of `0xb49f677943BC038e9857d61E7d053CaA2C1734C1`.

Before depositing amount, the contract is ensuring the amount being deposited is greater than `minAmountToDepositInUsd`.

The issue is in `DataFeed.sol` where while fetching the price via chainlink in `getDataInBase18()` function has used incorrect `_HEALTHY_DIFF` which is implemented as below:

```solidity
    uint256 private constant _HEALTHY_DIFF = 3 days;

    . . . some code


    function _getDataInBase18()
        private
        view
        returns (uint80 roundId, uint256 answer)
    {
        uint8 decimals = aggregator.decimals();
        (uint80 _roundId, int256 _answer, , uint256 updatedAt, ) = aggregator
            .latestRoundData();
        require(_answer > 0, "DF: feed is deprecated");
        require(
            // solhint-disable-next-line not-rely-on-time
            block.timestamp - updatedAt <= _HEALTHY_DIFF,      @audit // incorrect staleness period check
            "DF: feed is unhealthy"
        );
        roundId = _roundId;
        answer = uint256(_answer).convertToBase18(decimals);
    }
```

Here, `_HEALTHY_DIFF` is being used as heartbeat which is used to check the staleness of data within given time period and this is hardcoded as `3 days`. Chainlink's `EUR/USD` has heartbeat of `24 hours` i.e 1 days and this can be checked [here](https://data.chain.link/feeds/ethereum/mainnet/eur-usd)

The issue here is with the incorrect use of `_HEALTHY_DIFF` as `3 days` instead of chainlink's `24 hours` duration. 

`_HEALTHY_DIFF` used in contracts is actually `3` times longer than the Chainlink heartbeat that is `24 hours`, potentially introducing a significant delay in recognizing stale or outdated price data.

For EUR/USD, Chainlink specifically states that:

> A new answer is written when the offchain data moves more than the deviation threshold or 86400 seconds have passed since the last answer was written on chain.

Due to incorrect use of `_HEALTHY_DIFF` duration `_getDataInBase18()` function is affected and would behave incorrectly resulting in outdated and stale price in used contracts like DepositVault.deposit()

`_getDataInBase18()` function from `eurUsdDataFeed` contract as used in `DepositVault.sol` will use this hardcoded `3 days` heartbeat which means that the price can move up to 3 days before a price update is triggered. The result is that the on-chain price could be much different than the true EUR prices.

## Impact
The Chainlink heartbeat indicates the expected frequency of updates from the oracle. The Chainlink heartbeat on Ethereum for EUR/USD is 24 hours but the used `_HEALTHY_DIFF` as heartbeat in contract is `3 days` which 3 times longer than actual chainlink heartbeat which would result in stale prices.

A `_HEALTHY_DIFF` that is significantly longer than the heartbeat can lead to scenarios where  `DepositVault` contract accepts data that may no longer reflect current market conditions. Also, in volatile markets, a `3 days`  window leads to accepting outdated prices, increasing the risk of price slippage. The users would be heavily affected by this outdated price as returned by chainlink.

This incorrect and stale prices returned from current implementation would result in loss of users funds where EUR prices would be referred. This wont give the actual market prices of these assets and there could be huge price difference of these asset prices and can have adverse impact on users funds.

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L27

## Tool used
Manual Review

## Recommendation
Consider using `_HEALTHY_DIFF` as `24 hours` in Data feed contracts to align more closely with the Chainlink heartbeat on Ethereum, enhancing the relevance of the price data and `1 hours` for [Arbitrum mainnet](https://data.chain.link/feeds/arbitrum/mainnet/eur-usd).

```diff
-    uint256 private constant _HEALTHY_DIFF = 3 days;
+    uint256 private constant _HEALTHY_DIFF = 86400;
```

**Note**:
It should also be noted that, Midas also mentions about `IB01/USD` and it has also 24 hours heartbeat which can be checked [here](https://data.chain.link/feeds/ethereum/mainnet/ib01-usd) so this issue is also applicable to `IB01/USD` feeds as used in current implementation contracts.

Duplicate of #110

**Comment by WangSecurity** [comment]
This report will be invalidated based on the escalation on #110.
