### ISSUE TITLE
sandy - USDC blacklist and ``tokensReceiver`` being a single point of failure.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-midas-judging#163]
sandy

high

# USDC blacklist and ``tokensReceiver`` being a single point of failure.

## Summary
``tokensReceiver`` can't be updated once it is set and ``USDC`` has a blacklist mechanism(which is in scope). Thus, ``tokensReceiver`` getting blacklisted by ``USDC`` can render the protocol useless. But, Even though there is a mechanism to add new payment tokens, it is mentioned explicitly in the ``ReadMe`` that ``Only USDC and mTBILL will be used so only those will be in the scope of the audit``. 
 
## Vulnerability Detail
``tokensReceiver`` is the address to which ``USDC`` and ``mTokens`` is sent sent from ``deposit()`` function of ``DepositVault`` and ``redeem()`` function of ``RedemptionVault``.

```solidity
    function _tokenTransferFromUser(address token, uint256 amount) internal {
        IERC20(token).safeTransferFrom(msg.sender, tokensReceiver, amount.convertFromBase18(_tokenDecimals(token)));
    }
```

```solidity
    function deposit(address tokenIn, uint256 amountUsdIn) external onlyGreenlisted(msg.sender) whenNotPaused {
...
        _tokenTransferFromUser(tokenIn, amountUsdIn);
...

    }
```

```solidity
    function redeem(address tokenOut, uint256 amountTBillIn) external onlyGreenlisted(msg.sender) whenNotPaused {
...
        _tokenTransferFromUser(address(mTBILL), amountTBillIn);
...
    }
```

``tokensReceiver`` value is set during initialization and it can't be changed again and It is mentioned explicitly in the ``ReadMe`` that ``Only USDC and mTBILL will be used so only those will be in the scope of the audit``. Thus, no new payment token will be added as per ``ReadMe``.

## Impact
If ``tokensReceiver`` gets blacklisted by USDC, the whole protocol needs to redeployed again.

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/abstract/ManageableVault.sol#L82

## Tool used
Manual Review

## Recommendation
Add a method to modify the ``tokensReceiver`` in case ``tokensReceiver`` is blacklisted by ``USDC``.

**Comment by 0xSandyy** [comment]
Escalate

First of all:
> Non-Standard tokens: Issues related to tokens with non-standard behaviors, such as [weird-tokens](https://github.com/d-xo/weird-erc20) are not considered valid by default unless these tokens are explicitly mentioned in the README.

The ``README`` states:
> ERC20 token behaviours in scope
Tokens in the scope: mTBILL, USDC
Vulnerabilites derived from the following behaviours will only be considered valid if the issues exist in the tokens used by the protocol.

I want to emphasis on this part of the ``README``:
> Vulnerabilites derived from the following behaviours will only be considered valid if the issues exist in the tokens used by the protocol.

and ``Blocklists`` is in scope and this issue focuses on ``USDC Blocklists``.

At last:
> If the protocol team provides specific information in the README or CODE COMMENTS, that information stands above all judging rules.

Also, what makes this issue more serious is that ``tokensReceiver`` is a single point of failure and can't be updated once set and the protocol clearly states in the readme that:
> Only USDC and mTBILL will be used so only those will be in the scope of the audit.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> First of all:
> > Non-Standard tokens: Issues related to tokens with non-standard behaviors, such as [weird-tokens](https://github.com/d-xo/weird-erc20) are not considered valid by default unless these tokens are explicitly mentioned in the README.
> 
> The ``README`` states:
> > ERC20 token behaviours in scope
> Tokens in the scope: mTBILL, USDC
> Vulnerabilites derived from the following behaviours will only be considered valid if the issues exist in the tokens used by the protocol.
> 
> I want to emphasis on this part of the ``README``:
> > Vulnerabilites derived from the following behaviours will only be considered valid if the issues exist in the tokens used by the protocol.
> 
> and ``Blocklists`` is in scope and this issue focuses on ``USDC Blocklists``.
> 
> At last:
> > If the protocol team provides specific information in the README or CODE COMMENTS, that information stands above all judging rules.
> 
> Also, what makes this issue more serious is that ``tokensReceiver`` is a single point of failure and can't be updated once set and the protocol clearly states in the readme that:
> > Only USDC and mTBILL will be used so only those will be in the scope of the audit.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by maushish** [comment]
Invalid escalation
Sherlock has made strict rules for such types of findings in their [docs](https://docs.sherlock.xyz/audits/judging/judging):
![image](https://github.com/sherlock-audit/2024-05-midas-judging/assets/114429859/747f2058-357b-46d6-913d-12b09299a4c0)

**Comment by WangSecurity** [comment]
This rule applies here:

> Contract / Admin Address Blacklisting / Freezing: If a protocol's smart contracts or admin addresses get added to a "blacklist" and the functionality of the protocol is affected by this blacklist, this is not considered a valid issue.

If you still believe the rules about blacklist functionality shouldn't apply, please refer to my comment [here](https://github.com/sherlock-audit/2024-05-midas-judging/issues/175#issuecomment-2163105782).

Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xSandyy](https://github.com/sherlock-audit/2024-05-midas-judging/issues/163/#issuecomment-2156302091): rejected
