### ISSUE TITLE
MohammedRizwan - Malicious user can front run blacklist role transaction to prevent his address from redeem of tokens

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-midas-judging#164]
MohammedRizwan

medium

# Malicious user can front run blacklist role transaction to prevent his address from redeem of tokens

## Summary
Malicious greenlisted user can front run blacklist role transaction to prevent from redeem of tokens

## Vulnerability Detail
`GREENLISTED_ROLE` are restricted roles as per contest readme. only `GREENLISTED_ROLE` is allowed to redeem and deposit the tokens via `RedemptionVault.redeem()` and `DepositVault.deposit()` functions. 

The contracts has functionality to add as blacklisted user. 

> The admin can add someone to the blacklist when such person is considered as a risky wallet (for example, someone who acquired tokens by stealing them on a lending platform will likely be added to the blacklist). When blacklisted, you can’t send nor receive the token anymore.
 
However, such grant role of `BLACKLISTED_ROLE` to malicious accounts can be prevented by front running. Front running can be done either by sending a transaction with a higher gas price (usually tx are ordered in a block by the gas price / total fee), or by paying an additional fee to the validator if they manage to run their tx without reverting (i.e. by sending additional ETH to block.coinbase, hoping validator will notice it).

Possible Attack Path:

1) Alice is a very financially wealthy and cautious user who has a bot always examining the mempool for all possible blacklisting actions or monitoring of `BLACKLISTED_ROLE` to accounts by `BLACKLIST_OPERATOR_ROLE`. 

2) Alice has done something "illicit or nefarious" - against Meda's policies.

3) Medas attempts to blacklist one of Alice's wallets i.e granting his address with `BLACKLISTED_ROLE` to prevent redeem of his tokens.

4) Alice does not have to worry as her bot automatically front-runs the transactions granting his address to `BLACKLISTED_ROLE` submitted by Medas `BLACKLIST_OPERATOR_ROLE` address.

5) Alice immediatly calls `RedemptionVault.redeem()` with very higher gas fees so that his `mTBILL` tokens are [transferred](https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/RedemptionVault.sol#L74C40-L74C46) to token receiver and the redeem request can be successfully placed to get back his USDC or USD.

6) This way, Alice has successfully placed the redeem request and now she can get her tokens back.

Reference: https://github.com/sherlock-audit/2023-02-telcoin-judging/issues/63

## Impact
In simple words, Malicious user can bypass the blacklist mechanism i.e Malicious user could listen the mempool in order to check if he sees a transaction of blacklisting for his address i,e admin is granting his address with `BLACKLISTED_ROLE` , if that happens he could front run this transaction by sending a transaction with higher gas fee to redeem his funds to prevent them from permanent freezing. 

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/RedemptionVault.sol#L74

## Tool used
Manual Review

## Recommendation
Recommend an alternative mechanisms for blacklisting or prevention to mitigate front-running risks, or consider utilizing private transactions to prevent malicious users from monitoring the mempool.

**Comment by 0xRizwan** [comment]
@MxAxM Why this issue is excluded?

**Comment by MxAxM** [comment]
> @MxAxM Why this issue is excluded?

It has low impact as user can't interact with protocol anymore which is purpose of blacklisting, furthermore admins can mitigate this by providing high gas fees

**Comment by 0xMR0** [comment]
Escalate on behalf of @0xRizwan

**Comment by sherlock-admin3** [comment]
> Escalate on behalf of @0xRizwan 

You've deleted an escalation for this issue.

**Comment by 0xRizwan** [comment]
I believe this is valid issue and wrong excluded. In past, similar issue is accepted at sherlock as Medium severity. 

For example:https://github.com/sherlock-audit/2023-02-telcoin-judging/issues/63

**Comment by maushish** [comment]
Invalid escalation
According to me this one is a low/info vuln as the condition of such a scenario happening involves:
- The attacker is wealthy
- If Midas is blacklisting the attacker's addresses due to some illicit decisions, they can simply block the fund's transfer as it's mentioned in the docs that all RWAs conversions have been KYCed by banking authorities.
- Even after this if an attacker manages to request liquidation midas off-chain system could simply put a penalty on the attacker for the wrongdoing.

**Comment by 0xRizwan** [comment]
@pronobis4 Can you please check this issue?
