### ISSUE TITLE
sandy - Invalid assumption about the current price feed pair being used can lead to some implications.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-midas-judging#166]
sandy

high

# Invalid assumption about the current price feed pair being used can lead to some implications.

## Summary
The readme states:
> IB01/USD Price from Chainlink is RESTRICTED, as their documentation states that the price will only be updated during defined market hours (weekends and holidays excluded), so we assume the price is only stale if more than three days have passed.

But, the protocol doesn't use ``IB01/USD`` price from chainlink. Instead it uses ``EUR/USD`` price from chainlink but with the same assumption for staleness as ``IB01/USD``. This can lead to some implications.

## Vulnerability Detail
On Ethereum, ``IB01/USD`` price is based on ``UK_ETF`` market hours whereas ``EUR/USD`` is based on ``Forex`` market hours.
As per the [chainlink](https://docs.chain.link/data-feeds/selecting-data-feeds#market-hours) market hours docs, ``UK_ETF`` market hours is Monday-Friday and ``Forex`` market hours is ``S-F``.

Now, let's evaluate the assumption for ``IB01/USD``
> IB01/USD Price from Chainlink is RESTRICTED, as their documentation states that the price will only be updated during defined market hours (weekends and holidays excluded), so we assume the price is only stale if more than three days have passed.

It mentions `` the price is only stale if more than three days have passed``. The ``3`` days is due to the time difference from ``Friday-Monday`` during which ``UK_ETF`` market hours are closed and price is not updated.

Thus, for ``EUR/USD`` it should be ``2`` days from ``Friday - Sunday`` during which ``Forex`` market hours are closed.

## Impact
The ``DepositVault`` contract uses ``EUR/USD`` data feed.
```solidity
    IDataFeed public eurUsdDataFeed;
```
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/DepositVault.sol#L45

In the ``deposit()`` function, ``_validateAmountUsdIn()`` function is used to validate that that inputted USD amount >= minAmountToDepositInUsd().

and ``minAmountToDepositInUsd()`` function uses ``eurUsdDataFeed`` to get minimum ``USD`` amount.
```solidity
    function minAmountToDepositInUsd() public view returns (uint256) {
        return (minAmountToDepositInEuro * eurUsdDataFeed.getDataInBase18()) / 10 ** 18;
    }
```
In the ``DataFeed`` contract, ``_HEALTHY_DIFF`` is set to ``3 days`` instead of ``2 days`` for ``EUR/USD``. Thus, the ``_validateAmountUsdIn`` validates `` inputted USD amount `` with stale ``minAmountToDepositInUsd``.

Actual Impact:
Due to checking invalid difference of price feed data updated time in ``_getDataInBase18()`` function, 
```solidity
        require(
            // solhint-disable-next-line not-rely-on-time
            block.timestamp - updatedAt <= _HEALTHY_DIFF,
            "DF: feed is unhealthy"
        );
```
The price feed will return stale price for 1 day. ``EUR/USD`` has [deviation threshold](https://data.chain.link/feeds/ethereum/mainnet/eur-usd) of ``0.15%`` and the minimum amount to deposit is ``100,000 Euros``. Thus price can move up to ``0.149%`` in 1 day before it is updated again.

```solidity
0.149 / 100 * 100000 = 149$
``` 
Max amount of ``149$`` can move up and down for the minimum deposit amount from the actual market rate while depositing due to price being stale for 1 day.

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L27

## Tool used
Manual Review

## Recommendation
Set the ``_HEALTHY_DIFF`` to ``2 days`` instead of ``3 days``.

Duplicate of #110

**Comment by WangSecurity** [comment]
This report will be invalidated based on the escalation on #110.
