### ISSUE TITLE
Tri-pathi - DataFeed will return stale price due to large `_HEALTHY_DIFF` than heartbeat

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-midas-judging#170]
Tri-pathi

medium

# DataFeed will return stale price due to large `_HEALTHY_DIFF` than heartbeat

## Summary

The `DataFeed` contract uses Chainlink's price feed for obtaining the EUR/USD price. It employs a variable _HEALTHY_DIFF set to 3 days to validate the freshness of the price data. However, this duration is significantly longer than the Chainlink heartbeat for the EUR/USD data feed, which is 24 hours on Ethereum and 1 hour on Arbitrum

## Vulnerability Detail

```solidity
    function getDataInBase18() external view returns (uint256 answer) {
        (, answer) = _getDataInBase18();
    }

    function _getDataInBase18()
        private
        view
        returns (uint80 roundId, uint256 answer)
    {
        uint8 decimals = aggregator.decimals();
        (uint80 _roundId, int256 _answer, , uint256 updatedAt, ) = aggregator
            .latestRoundData();//@audit-issue roundId is not checked 
        require(_answer > 0, "DF: feed is deprecated");
        require(
            // solhint-disable-next-line not-rely-on-time
            block.timestamp - updatedAt <= _HEALTHY_DIFF, 
            "DF: feed is unhealthy"
        );
        roundId = _roundId;
        answer = uint256(_answer).convertToBase18(decimals); 
    }
```

it checks if lastupdate price if within 3 days `block.timestamp - updatedAt <= _HEALTHY_DIFF`.  which is much longer than heartbeat of used pricefeed.

## Impact
The Chainlink heartbeat indicates the expected frequency of updates from the oracle. The Chainlink heartbeat on Ethereum for EUR/USD is 24 hour [1](https://data.chain.link/feeds/ethereum/mainnet/eur-usd) and 1 hour in Arbitrum [2](https://data.chain.link/feeds/arbitrum/mainnet/eur-usd)

But the defined _HEALTHY_DIFF is 3 days
A _HEALTHY_DIFF that is significantly longer than the heartbeat can lead to scenarios where the `Datafeed` library accepts data that may no longer reflect current market conditions. Also, in volatile markets, a 3-day window leads to accepting outdated prices, increasing the risk of price slippage.

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L27
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L75
## Tool used

Manual Review

## Recommendation
Consider reducing the _HEALTHY_DIFF to align more closely with the Chainlink heartbeat on Ethereum and Arbitrum, enhancing the relevance of the price data.

Duplicate of #110

**Comment by WangSecurity** [comment]
This report will be invalidated based on the escalation on #110.
