### ISSUE TITLE
carlitox477 - Oracle staleness check too long for IB01/USD

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-midas-judging#18]
carlitox477

medium

# Oracle staleness check too long for IB01/USD

## Summary
Length of staleness check is not safe to prevent stale prices to be used by Midas

## Vulnerability Detail
[Docs states a heartbeat of 24 hours (86400 seconds) for EUR/USD data feed](https://docs.chain.link/data-feeds/price-feeds/addresses?network=ethereum&page=1&search=eur), while [blockchain scanner shows that this period of time is respected even in non tradable hours days (weekends)](https://etherscan.io/txs?a=0x5EE6Ee50c1cB3E8Da20eE83D57818184387433e8&p=1).

Currently Midas check for a staleness period of 3 days, which can lead to use stale prices if for any reason chainlink does not update its price feed for 1 to 3 days.

## Impact
Oracle staleness length check is not correct.

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L27
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L75

## Tool used
Manual Review

## Recommendation
Use a safer period like `1 days + 12 hours` for IB01/USD price feed staleness check instead of 3 days. It's important to notice that chainlink sent a dummy update in not tradable days (weekends/holidays/etc), therefore the integrity of the protocol integration is not compromised

Duplicate of #110

**Comment by WangSecurity** [comment]
This report will be invalidated based on the escalation on #110.
