### ISSUE TITLE
plairfx - `MidasAccessControl::_setupRoles` will not change the `DEFAULT_ADMIN_ROLE` used in `WithMidasAccesControl`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-midas-judging#184]
plairfx

high

# `MidasAccessControl::_setupRoles` will not change the `DEFAULT_ADMIN_ROLE` used in `WithMidasAccesControl`

## Summary
When `_setupRoles` is called it will not change the `DEFAULT_ADMIN_ROLE` used in `WithMidasAccessControl` which will let the DEFAULT_ADMIN_ROLE stay `0x00` which means users with no admin roles can call `changeAggregator` function inside `DataFeed.sol` and `setMetadata` inside MTBill.sol`.

withMidasAccessControl will not directly inherit the change made as it uses a separate variable named `DEFAULT_ADMIN_ROLE` and `AccessControlUpgrade` does aswell.

## Vulnerability Detail
Users with no roles will be able to use admin functions like `changeAggregator` which can change the DataFeed for the protocol, which can cause a function like

```javascript
   /**
     * @notice minAmountToDepositInEuro converted to USD in base18
     */
    function minAmountToDepositInUsd() public view returns (uint256) {
        return
            (minAmountToDepositInEuro * eurUsdDataFeed.getDataInBase18()) /
            10**18;
    }
```

To receive other price data which is how user can deposit under the 100k limit set by the protocol team.

## Impact
User can change the protocol invariant of having min 100k deposit entry.

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/a4a3cc23bb891913ce44665a4cdea9f5c1190f6c/midas-contracts/contracts/access/WithMidasAccessControl.sol#L19

https://github.com/sherlock-audit/2024-05-midas/blob/a4a3cc23bb891913ce44665a4cdea9f5c1190f6c/midas-contracts/contracts/feeds/DataFeed.sol#L42-#L49

https://github.com/sherlock-audit/2024-05-midas/blob/a4a3cc23bb891913ce44665a4cdea9f5c1190f6c/midas-contracts/contracts/mTBILL.sol#L79-#L84

## Tool used

Manual Review

## Recommendation
Make sure to set the DEFAULT_ADMIN_ROLE also inside `withMidasAccessControl` to the admin address at the `_setupRoles` function.

**Comment by plairfx** [comment]
I cannot escalate, so here my thoughts.

The role `Default_Admin_Role` is not inside `MidasAccessControlRoles` where all the roles get setup with keccak256.


```javascript
// SPDX-License-Identifier: MIT
pragma solidity 0.8.9;

/**
 * @title MidasAccessControlRoles
 * @notice Base contract that stores all roles descriptors
 * @author RedDuck Software
 */
abstract contract MidasAccessControlRoles {
    /**
     * @notice actor that can change green list statuses of addresses
     */
    bytes32 public constant GREENLIST_OPERATOR_ROLE =
        keccak256("GREENLIST_OPERATOR_ROLE");

    /**
     * @notice actor that can change black list statuses of addresses
     */
    bytes32 public constant BLACKLIST_OPERATOR_ROLE =
        keccak256("BLACKLIST_OPERATOR_ROLE");

    /**
     * @notice actor that can mint mTBILL
     */
    bytes32 public constant M_TBILL_MINT_OPERATOR_ROLE =
        keccak256("M_TBILL_MINT_OPERATOR_ROLE");

    /**
     * @notice actor that can burn mTBILL
     */
    bytes32 public constant M_TBILL_BURN_OPERATOR_ROLE =
        keccak256("M_TBILL_BURN_OPERATOR_ROLE");

    /**
     * @notice actor that can pause mTBILL
     */
    bytes32 public constant M_TBILL_PAUSE_OPERATOR_ROLE =
        keccak256("M_TBILL_PAUSE_OPERATOR_ROLE");

    /**
     * @notice actor that have admin rights in deposit vault
     */
    bytes32 public constant DEPOSIT_VAULT_ADMIN_ROLE =
        keccak256("DEPOSIT_VAULT_ADMIN_ROLE");

    /**
     * @notice actor that have admin rights in redemption vault
     */
    bytes32 public constant REDEMPTION_VAULT_ADMIN_ROLE =
        keccak256("REDEMPTION_VAULT_ADMIN_ROLE");

    /**
     * @notice actor that is greenlisted
     */
    bytes32 public constant GREENLISTED_ROLE = keccak256("GREENLISTED_ROLE");

    /**
     * @notice actor that is blacklisted
     */
    bytes32 public constant BLACKLISTED_ROLE = keccak256("BLACKLISTED_ROLE");
}
```

This means the  `DEFAULT_ADMIN_ROLE` will still have the same value as in the `AccessControlUpgradable`  and `WithMidasAccesControl`-> default bytes 32 `0x00`.


So when `onlyRole` modifier is called it will compare the `0x00` bytes32 value with the users role which will also be the basic value `0x00`

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> The role `Default_Admin_Role` is not inside `MidasAccessControlRoles` where all the roles get setup with keccak256.
> 
> 
> ```javascript
> // SPDX-License-Identifier: MIT
> pragma solidity 0.8.9;
> 
> /**
>  * @title MidasAccessControlRoles
>  * @notice Base contract that stores all roles descriptors
>  * @author RedDuck Software
>  */
> abstract contract MidasAccessControlRoles {
>     /**
>      * @notice actor that can change green list statuses of addresses
>      */
>     bytes32 public constant GREENLIST_OPERATOR_ROLE =
>         keccak256("GREENLIST_OPERATOR_ROLE");
> 
>     /**
>      * @notice actor that can change black list statuses of addresses
>      */
>     bytes32 public constant BLACKLIST_OPERATOR_ROLE =
>         keccak256("BLACKLIST_OPERATOR_ROLE");
> 
>     /**
>      * @notice actor that can mint mTBILL
>      */
>     bytes32 public constant M_TBILL_MINT_OPERATOR_ROLE =
>         keccak256("M_TBILL_MINT_OPERATOR_ROLE");
> 
>     /**
>      * @notice actor that can burn mTBILL
>      */
>     bytes32 public constant M_TBILL_BURN_OPERATOR_ROLE =
>         keccak256("M_TBILL_BURN_OPERATOR_ROLE");
> 
>     /**
>      * @notice actor that can pause mTBILL
>      */
>     bytes32 public constant M_TBILL_PAUSE_OPERATOR_ROLE =
>         keccak256("M_TBILL_PAUSE_OPERATOR_ROLE");
> 
>     /**
>      * @notice actor that have admin rights in deposit vault
>      */
>     bytes32 public constant DEPOSIT_VAULT_ADMIN_ROLE =
>         keccak256("DEPOSIT_VAULT_ADMIN_ROLE");
> 
>     /**
>      * @notice actor that have admin rights in redemption vault
>      */
>     bytes32 public constant REDEMPTION_VAULT_ADMIN_ROLE =
>         keccak256("REDEMPTION_VAULT_ADMIN_ROLE");
> 
>     /**
>      * @notice actor that is greenlisted
>      */
>     bytes32 public constant GREENLISTED_ROLE = keccak256("GREENLISTED_ROLE");
> 
>     /**
>      * @notice actor that is blacklisted
>      */
>     bytes32 public constant BLACKLISTED_ROLE = keccak256("BLACKLISTED_ROLE");
> }
> ```
> 
> This means the  `DEFAULT_ADMIN_ROLE` will still have the same value as in the `AccessControlUpgradable`  and `WithMidasAccesControl`-> default bytes 32 `0x00`.
> 
> 
> So when `onlyRole` modifier is called it will compare the `0x00` bytes32 value with the users role which will also be the basic value `0x00`

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by plairfx** [comment]
@MxAxM 
My explanation is above friend.

**Comment by MxAxM** [comment]
> @MxAxM My explanation is above friend.

changeAggregator requires msg.sender to be DEFAULT_ADMIN_ROLE  which is address 0, so it's not possible

**Comment by plairfx** [comment]
@MxAxM 

It uses the onlyRole modifier  from `WithMidasAccessControl.sol`

It does not compare the DEFAULT_ADMIN_ROLE address but it compares the bytes32 number affialiated with the role,

The default value of a bytes32 = 0x00

So it will check if an account has a  role, and went a user has no role it will have a basic bytes32 number
0x00 which is equal to what is set inside the  `WithMidasAccessControl.sol `that gets imported by `DataFeed.sol` which is:


```javascript
    /**
     * @notice admin role
     */
    bytes32 public constant DEFAULT_ADMIN_ROLE = 0x00;
```


```javascript
    modifier onlyRole(bytes32 role, address account) {
        _onlyRole(role, account);
        _;
    }

```

Which calls the internal role function

```javascript
   function _onlyRole(bytes32 role, address account) internal view {
        require(accessControl.hasRole(role, account), "WMAC: hasnt role");
    }
    
    // Calls this from openzeppelin upgradable ->
    
        function hasRole(bytes32 role, address account) public view virtual returns (bool) {
        AccessControlStorage storage $ = _getAccessControlStorage();
        return $._roles[role].hasRole[account];
    }
    
    // HasRole calls this
    
       function _getAccessControlStorage() private pure returns (AccessControlStorage storage $) {
        assembly {
            $.slot := AccessControlStorageLocation
        }
    }

```

This will check if a bytes32 is equal to the users role, which is why all the bytes32 inside `MidasAccessControlRoles.sol`, are to see if a user role is equal to the bytes32 data from that file. (Which is why it gets keccak256.

Hope i explained it better.

**Comment by plairfx** [comment]
Example 1  `changeAggregator`

1. Non-admin user calls `changeAggregator`
2. onlyRole modifier gets called which compares the `DEFAULT_ADMIN_ROLE` bytes32 to the USERS bytes32 role.
3. `DEFAULT_ADMIN_ROLE` equals 0x00, and in solidity bytes32 default value = 0x00, which will mean USERS bytes32 role and the `DEFAULT_ADMIN_ROLE` will be the same.
4. USER will be able to change the aggregator,



Example 2 setMetaData `mTBILL.sol`
1. USER calls setMetaData,
2. onlyRole modifier gets called which compares the `DEFAULT_ADMIN_ROLE` bytes32 to the USERS bytes32 role.
3. `DEFAULT_ADMIN_ROLE` equals 0x00, and in solidity bytes32 default value = 0x00, which will mean USERS bytes32 role and the `DEFAULT_ADMIN_ROLE` will be the same.
4. USER will be able to change the aggregator,

(THIS WILL NOT WORK)
EXAMPLE 3 pause `MTBILL.sol`
1. USER Calls pause inside,
2. onlyRole modifier gets called which compares `M_TBILL_PAUSE_OPERATOR_ROLE`
3. This will not be equal to the role which will revert, as `M_TBILL_PAUSE_OPERATOR_ROLE`

Because 0x00 (user default bytes32 role) will not equal to the role inside `MIdasAccesControlRoles` that gets keccak256  in bytes32.

I believe this a  valid issue and an escalation,

I hope this post and above provide a better picture as the address does not compared, but the role bytes 32 itself of an user.

Thank you in advance @MxAxM

**Comment by MxAxM** [comment]
> Example 1 `changeAggregator`
> 
>     1. Non-admin user calls `changeAggregator`
> 
>     2. onlyRole modifier gets called which compares the `DEFAULT_ADMIN_ROLE` bytes32 to the USERS bytes32 role.
> 
>     3. `DEFAULT_ADMIN_ROLE` equals 0x00, and in solidity bytes32 default value = 0x00, which will mean USERS bytes32 role and the `DEFAULT_ADMIN_ROLE` will be the same.
> 
>     4. USER will be able to change the aggregator,
> 
> 
> Example 2 setMetaData `mTBILL.sol`
> 
>     1. USER calls setMetaData,
> 
>     2. onlyRole modifier gets called which compares the `DEFAULT_ADMIN_ROLE` bytes32 to the USERS bytes32 role.
> 
>     3. `DEFAULT_ADMIN_ROLE` equals 0x00, and in solidity bytes32 default value = 0x00, which will mean USERS bytes32 role and the `DEFAULT_ADMIN_ROLE` will be the same.
> 
>     4. USER will be able to change the aggregator,
> 
> 
> (THIS WILL NOT WORK) EXAMPLE 3 pause `MTBILL.sol`
> 
>     1. USER Calls pause inside,
> 
>     2. onlyRole modifier gets called which compares `M_TBILL_PAUSE_OPERATOR_ROLE`
> 
>     3. This will not be equal to the role which will revert, as `M_TBILL_PAUSE_OPERATOR_ROLE`
> 
> 
> Because 0x00 (user default bytes32 role) will not equal to the role inside `MIdasAccesControlRoles` that gets keccak256 in bytes32.
> 
> I believe this a valid issue and an escalation,
> 
> I hope this post and above provide a better picture as the address does not compared, but the role bytes 32 itself of an user.
> 
> Thank you in advance @MxAxM

I reviewed the codebase, it seems default admin role is initialized at _setupRoles()
https://github.com/sherlock-audit/2024-05-midas/blob/a4a3cc23bb891913ce44665a4cdea9f5c1190f6c/midas-contracts/contracts/access/MidasAccessControl.sol#L69-L71

**Comment by plairfx** [comment]
![image](https://github.com/sherlock-audit/2024-05-midas-judging/assets/146370891/c7db2d57-4ac3-4282-a6e7-2bc4ba188b12)


![image](https://github.com/sherlock-audit/2024-05-midas-judging/assets/146370891/f53db2e2-9064-4e1d-9066-8b814a12af61)


The protocol uses v.4.9.0 of openzeppelin upgradable,

This will only grant the role to the admin user. and not set the role as admin user as you said in your previous reply.


@MxAxM

**Comment by plairfx** [comment]
If DEFAULT_ADMIN_ROLE was 

keccak256 like the other roles

But the DEFAULT_ADMIN_ROLE is not inside this file

https://github.com/sherlock-audit/2024-05-midas/blob/a4a3cc23bb891913ce44665a4cdea9f5c1190f6c/midas-contracts/contracts/access/MidasAccessControlRoles.sol

```javascript
// SPDX-License-Identifier: MIT
pragma solidity 0.8.9;

/**
 * @title MidasAccessControlRoles
 * @notice Base contract that stores all roles descriptors
 * @author RedDuck Software
 */
abstract contract MidasAccessControlRoles {
    /**
     * @notice actor that can change green list statuses of addresses
     */
    bytes32 public constant GREENLIST_OPERATOR_ROLE =
        keccak256("GREENLIST_OPERATOR_ROLE");

    /**
     * @notice actor that can change black list statuses of addresses
     */
    bytes32 public constant BLACKLIST_OPERATOR_ROLE =
        keccak256("BLACKLIST_OPERATOR_ROLE");

    /**
     * @notice actor that can mint mTBILL
     */
    bytes32 public constant M_TBILL_MINT_OPERATOR_ROLE =
        keccak256("M_TBILL_MINT_OPERATOR_ROLE");

    /**
     * @notice actor that can burn mTBILL
     */
    bytes32 public constant M_TBILL_BURN_OPERATOR_ROLE =
        keccak256("M_TBILL_BURN_OPERATOR_ROLE");

    /**
     * @notice actor that can pause mTBILL
     */
    bytes32 public constant M_TBILL_PAUSE_OPERATOR_ROLE =
        keccak256("M_TBILL_PAUSE_OPERATOR_ROLE");

    /**
     * @notice actor that have admin rights in deposit vault
     */
    bytes32 public constant DEPOSIT_VAULT_ADMIN_ROLE =
        keccak256("DEPOSIT_VAULT_ADMIN_ROLE");

    /**
     * @notice actor that have admin rights in redemption vault
     */
    bytes32 public constant REDEMPTION_VAULT_ADMIN_ROLE =
        keccak256("REDEMPTION_VAULT_ADMIN_ROLE");

    /**
     * @notice actor that is greenlisted
     */
    bytes32 public constant GREENLISTED_ROLE = keccak256("GREENLISTED_ROLE");

    /**
     * @notice actor that is blacklisted
     */
    bytes32 public constant BLACKLISTED_ROLE = keccak256("BLACKLISTED_ROLE");
}
```

It would had been no problem as the role would had not been the default value of 0x00 that every user will have.

@MxAxM

**Comment by plairfx** [comment]
I have just double checked the openzeppelin library to make sure this is an issue, and is not as openzeppelin uses another system to showcase that even when the DEFAULT_ADMIN_ROLE is equal to 0x00, another usew ith the same bytes32 will not be able to have the DEFAULT_ADMIN_ROLE,

Sorry should had done more DD, thanks btw for the replies  @MxAxM , valuable lesson for me.
