### ISSUE TITLE
MohammedRizwan - Possible revert or DOS in case of USD wire transfer in `DepositVault.deposit()`

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-midas-judging#186]
MohammedRizwan

medium

# Possible revert or DOS in case of USD wire transfer in `DepositVault.deposit()`

## Summary
Possible revert or DOS in case of USD wire transfer in `DepositVault.deposit()`

## Vulnerability Detail
The greenlisted user can deposit the tokens i.e USDC directly into the Midas Protocol or USD Bank wire transfer.

Per Midas documentation, USD wire transfer for deposits is also allowed.

> Issuance: Midas performs a [KYC ](https://docs.midas.app/additional-topics/glossary#know-your-customer-kyc)& [AML ](https://docs.midas.app/additional-topics/glossary#anti-money-laundering-laws-aml)check on investors intending to mint mTBILL by depositing USDC directly into the Midas Protocol or USD Bank wire.

`DepositVault.deposit()` is implemented as:

```solidity
    function deposit(address tokenIn, uint256 amountUsdIn)
        external
        onlyGreenlisted(msg.sender)
        whenNotPaused
    {
        address user = msg.sender;

@>      _requireTokenExists(tokenIn);        @audit // point 1

        lastRequestId.increment();
        uint256 requestId = lastRequestId.current();

        if (!isFreeFromMinDeposit[user]) {
            _validateAmountUsdIn(user, amountUsdIn);
        }
        require(amountUsdIn > 0, "DV: invalid amount");

        totalDeposited[user] += amountUsdIn;
@>      _tokenTransferFromUser(tokenIn, amountUsdIn);       @audit // point 2

        emit Deposit(requestId, user, tokenIn, amountUsdIn);
    }
```

For USD wire transfer which is offchain transfer, the tokenIn will be `MANUAL_FULLFILMENT_TOKEN`

```solidity
    /**
     * @notice address that represents off-chain USD bank transfer
     */
    address public constant MANUAL_FULLFILMENT_TOKEN = address(0x0);
 ```

Two points important for `MANUAL_FULLFILMENT_TOKEN` transfers:

1) `DepositVault.deposit()` checks `tokenIn` passsed as argument really exists or not. This is done by ` _requireTokenExists(tokenIn)` which is implemented as:

```solidity
    function _requireTokenExists(address token) internal view virtual {
        require(_paymentTokens.contains(token), "MV: token not exists");
    }
```

so, if the `MANUAL_FULLFILMENT_TOKEN` is added as payment token then the condition will pass or it will revert. To be noted while redeem, for tokenOut, `MANUAL_FULLFILMENT_TOKEN` is early returned which can be checked [here](https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/RedemptionVault.sol#L91)

2) Now, the last step is to transfer the `tokenIn` to tokenReceiver address so that mTBill tokens can be deposited to users address. This is done by `_tokenTransferFromUser()` which is implemented as:

```solidity
    function _tokenTransferFromUser(address token, uint256 amount) internal {
        IERC20(token).safeTransferFrom(
            msg.sender,
            tokensReceiver,
            amount.convertFromBase18(_tokenDecimals(token))    
        );                                                     
    }
```

This transfer the `tokenIn` from `msg.sender` to `tokensReceiver` address but `MANUAL_FULLFILMENT_TOKEN` is nothing but address(0) and its not a token address nor have any private key so tokens transfer is not possible here. The function will probably revert or DOS in case of USD wire transfer. Users wont be able to successfully register the deposit request in case of USD wire transfer due to possible revert or DOS.

## Impact
Users wont be able to successfully register the deposit or Issuance request in case of USD wire transfer due to possible revert or DOS as explained above.

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/DepositVault.sol#L109

## Tool used
Manual Review

## Recommendation
Handle the case when the `tokenIn` is a USD wire transfer by users. 

I would suggest to early return if tokenIn is `MANUAL_FULLFILMENT_TOKEN` as done in `RedemptionVault.sol`, similar approach could be done when validating token existence and transfer of tokenIn to tokensReceiver.

**Comment by 0xRizwan** [comment]
@MxAxM Why this issue is excluded?

**Comment by MxAxM** [comment]
> @MxAxM Why this issue is excluded?

It seems deposit function is not designed for USD wire transfers as it handles normal ERC20 transfers

**Comment by 0xMR0** [comment]
Escalate on behalf of @0xRizwan

**Comment by sherlock-admin3** [comment]
> Escalate on behalf of @0xRizwan

You've deleted an escalation for this issue.

**Comment by 0xRizwan** [comment]
I believe, this issue is incorrectly excluded and its a valid issue.

> It seems deposit function is not designed for USD wire transfers as it handles normal ERC20 transfers

@MxAxM Per Midas documentation, USD wire transfer for deposits is also allowed:

> Issuance: Midas performs a [KYC ](https://docs.midas.app/additional-topics/glossary#know-your-customer-kyc)& [AML ](https://docs.midas.app/additional-topics/glossary#anti-money-laundering-laws-aml)check on investors intending to mint mTBILL by depositing USDC directly into the Midas Protocol or USD Bank wire.

The `deposit()` function wont work expectedly if the user has `wire` USD transfer. As a recommendation, I would suggest to early return if tokenIn is `MANUAL_FULLFILMENT_TOKEN` as done in `RedemptionVault.sol`, similar approach could be done when validating token existence and transfer of tokenIn to tokensReceiver.

**Comment by maushish** [comment]
Invalid escalation
- USD wire transfers and minting of mTBILLs are done off-chain.
- For any wired amount the RWA owner (user ) will be minted mTBILLs in their given wallet address 
- There is no need of any mechanism here as this is completely centralized off-chain process.

**Comment by 0xRizwan** [comment]
@pronobis4 Can you please check this issue?
