### ISSUE TITLE
Gas optimization

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-midas-judging#189]
# Gas optimization

Low/Info issue submitted by **tpiliposian**

## Summary

In the `deposit()` function of the `DepositVault.sol` contract, the `require` statement to validate the input amount occurs after several operations. By moving this `require` statement to an earlier position in the function, gas consumption can potentially be reduced by avoiding unnecessary computation.

## Vulnerability Detail

The vulnerability lies in the current placement of the `require` statement, which occurs after certain operations in the function. This means that gas is expended on these operations even if the input amount is invalid, leading to potential gas inefficiency.

```solidity
       require(amountUsdIn > 0, "DV: invalid amount");
```

## Impact

The impact of the current placement of the `require` statement is primarily on gas consumption.

## Code Snippet

https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/DepositVault.sol#L91-L112

## Tool used

Manual Review

## Recommendation

It is recommended to move the `require` statement to an earlier position in the `deposit()` function, immediately after function entry, to optimize gas consumption.

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/RedDuck-Software/midas-contracts/pull/43

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
