### ISSUE TITLE
Same Heartbeat Check For All Price Feeds

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-midas-judging#194]
# Same Heartbeat Check For All Price Feeds

Low/Info issue submitted by **petarP1998**

## Summary
The `DataFeed` contract manages multiple price feeds, providing a grace period of 3 days before considering data potentially stale if not updated within the specified timeframe.

## Vulnerability Detail
The `DataFeed` contract utilizes Chainlink's AggregatorV3Interface for obtaining price data. It incorporates a constant `_HEALTHY_DIFF` to ensure that the data remains current within a predefined interval. However, there is a vulnerability related to the handling of inactive data feeds.

If a data feed remains inactive for a duration exceeding the specified heartbeat interval (e.g., 12 hours), the contract may incorrectly perceive the data as valid during the subsequent 3-day grace period. This scenario could lead to the utilization of stale or outdated information within the contract's operations.

It's noteworthy that this contract is intended for deployment on both Ethereum and Arbitrum. On Arbitrum, the heartbeat interval for the EUR/USD price feed is 1 hour, whereas on Ethereum, it is 24 hours. This discrepancy in heartbeat intervals across different chains introduces additional complexity to the vulnerability.

https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L64-L80

## Impact
- **Stale Data Risk**: The main impact of this vulnerability is the increased risk of stale data. If a price feed becomes inactive for a period longer than the specified heartbeat interval (in this case, 12 hours), the contract may incorrectly consider the data as valid during the grace period of 3 days. This can lead to inaccurate price information being used in financial calculations, trading algorithms, and other critical processes.
    
- **Financial Losses**: Incorrect or outdated price data can result in financial losses, especially in decentralized finance (DeFi) applications where precise and timely information is crucial for decision-making. Users relying on the data provided by the DataFeed contract may make suboptimal or erroneous financial decisions, leading to potential monetary losses.
    
- **Operational Disruption**: Inaccurate price data can disrupt the operation of dependent smart contracts and applications. This can manifest as incorrect execution of trades, incorrect asset valuations, or disruptions in automated processes, impacting the overall functionality and reliability of the affected systems.

## Code Snippet
```solidity
uint256 private constant _HEALTHY_DIFF = 3 days;

require(block.timestamp - updatedAt <= _HEALTHY_DIFF,"DF: feed is unhealthy");
```

## Tool used
Manual Review

## Recommendation
Implement a mechanism to allow for different grace periods for each price feed based on their individual update intervals. This ensures that the grace period aligns with the specific characteristics of each feed, minimizing the risk of relying on stale data.

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/RedDuck-Software/midas-contracts/pull/46

**Comment by pronobis4** [comment]
adding your nickname to the audit is a very bad practice @petarP1998

**Comment by peterP1998** [comment]
I think it's added by default by sherlock, because this issue is marked as Low, you can take a look at other issues reported as low.

**Comment by peterP1998** [comment]
> The protocol team fixed this issue in the following PRs/commits: https://github.com/RedDuck-Software/midas-contracts/pull/46

Could you please refer this to https://github.com/sherlock-audit/2024-05-midas-judging/issues/110

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
