### ISSUE TITLE
ZdravkoHr. - Hardcoding the same heatbeat for different oracles is dangerous

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-midas-judging#31]
ZdravkoHr.

medium

# Hardcoding the same heatbeat for different oracles is dangerous

## Summary
The [DataFeed](https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol) contract has hardcoded the hearbeat of all oracles to be 3 days. This is dangerous because different Chainlink oracles have different heartbeats.

## Vulnerability Detail
The `_HEALTY_DIFF` is hardcoded for 3 days in the DataFeed contract.
```solidity
    uint256 private constant _HEALTHY_DIFF = 3 days;
```
Currently, the DataFeed contract is used [here](https://github.com/sherlock-audit/2024-05-midas/blob/a4a3cc23bb891913ce44665a4cdea9f5c1190f6c/midas-contracts/contracts/DepositVault.sol#L137C1-L141C6) when depositing to check the EUR/USD price.
```solidity
    function minAmountToDepositInUsd() public view returns (uint256) {
        return
            (minAmountToDepositInEuro * eurUsdDataFeed.getDataInBase18()) /
            10**18;
    }
```

Assuming the README talks about IB01/USD price feeds, this contract will probably be used for more than one feed.

>[!Caution]
> The same contract will be deployed both on Ethereum and Arbitrum 

There is a difference between the EUR/USD price feed on these two chains.

The heartbeat for the [Ehtreum](https://data.chain.link/feeds/ethereum/mainnet/eur-usd) data feed is `24 hours`.
The heartbeat for the [Arbitrum](https://data.chain.link/feeds/arbitrum/mainnet/eur-usd) data feed is `1 hour`.

## Impact
In the above example with the two feeds on the different chains, having a hardcoded heartbeat value of 3 days would allow a staleness for 72 updates - this is huge and can have detrimental consequences.

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol
https://github.com/sherlock-audit/2024-05-midas/blob/a4a3cc23bb891913ce44665a4cdea9f5c1190f6c/midas-contracts/contracts/DepositVault.sol#L137C1-L141C6
## Tool used

Manual Review

## Recommendation
Instead of hardcoding the heartbeat value, set it on initialization per feed contract.

Duplicate of #110

**Comment by WangSecurity** [comment]
This report will be invalidated based on the escalation on #110.
