### ISSUE TITLE
nisedo - Inappropriate Stale Check for Oracle Price Feeds Causes Potential Financial Discrepancies

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-midas-judging#34]
nisedo

medium

# Inappropriate Stale Check for Oracle Price Feeds Causes Potential Financial Discrepancies

## Summary
The DataFeed contract uses a stale check of **3 days** for the Chainlink price feeds, which is appropriate for the IB01/USD price feed but not for the EUR/USD price feeds on Ethereum Mainnet and Arbitrum Mainnet. The latter feeds have heartbeats of **86400 seconds (1 day)** and **3600 seconds (1 hour)**, respectively, leading to potential reliance on outdated data.

## Vulnerability Detail
The `_HEALTHY_DIFF` constant in the DataFeed contract is set to **3 days** (259200 seconds). [Source](https://data.chain.link/feeds/ethereum/mainnet/ib01-usd)

This stale check duration is not suitable for EUR/USD price feeds which have significantly shorter heartbeats:
- The EUR/USD price feed on Ethereum Mainnet has a heartbeat of **86400** seconds (1 day). [Source](https://data.chain.link/feeds/ethereum/mainnet/eur-usd)
- The EUR/USD price feed on Arbitrum Mainnet has a heartbeat of **3600** seconds (1 hour). [Source](https://data.chain.link/feeds/arbitrum/mainnet/eur-usd)

Consequently, the contract might use price data that is up to **3 days old**, which is significantly outdated given the expected update frequency of these feeds.

## Impact
Using outdated data can have significant repercussions for the protocol and users that might deposit amounts based on stale conversion rates, causing them to either pay less than they should or more than they should for their first deposit. This can lead to unfair advantages or penalties.

## Code Snippet
[DataFeed.sol#L24-L27](https://github.com/sherlock-audit/2024-05-midas/blob/a4a3cc23bb891913ce44665a4cdea9f5c1190f6c/midas-contracts/contracts/feeds/DataFeed.sol#L24-L27)
```solidity
    /**
     * @dev healty difference between `block.timestamp` and `updatedAt` timestamps
     */
    uint256 private constant _HEALTHY_DIFF = 3 days;
```
[DataFeed.sol#L70-L77](https://github.com/sherlock-audit/2024-05-midas/blob/a4a3cc23bb891913ce44665a4cdea9f5c1190f6c/midas-contracts/contracts/feeds/DataFeed.sol#L70-L77)
```solidity
        (uint80 _roundId, int256 _answer, , uint256 updatedAt, ) = aggregator
            .latestRoundData();
        require(_answer > 0, "DF: feed is deprecated");
        require(
            block.timestamp - updatedAt <= _HEALTHY_DIFF,
            "DF: feed is unhealthy"
        );
```

## Tool used
Manual Review

## Recommendation
Adjust the `_HEALTHY_DIFF` constant to match the heartbeat of the specific price feed being used.

Duplicate of #110

**Comment by WangSecurity** [comment]
This report will be invalidated based on the escalation on #110.
