### ISSUE TITLE
araj - `DataFeed::_HEALTHY_DIFF` is very high than recommended

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-midas-judging#41]
araj

medium

# `DataFeed::_HEALTHY_DIFF` is very high than recommended

## Summary
`DataFeed::_HEALTHY_DIFF = 3 days` is very high than recommended by chainlink

## Vulnerability Detail
DataFeed is using `_HEALTHY_DIFF = 3 days` for checking `stale` price but this is very `high` as compared to what recommended by chainlink ie `1 day`, which means dataFeed can still `return` stale price because price can change within `1 day` period
```solidity
 uint256 private constant _HEALTHY_DIFF = 3 days;
```

## Impact
Stale price can be used 

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L27C4-L27C53
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L73C7-L77C11

## Tool used
Manual Review

## Recommendation
`Use` 1 days as `_HEALTHY_DIFF`

Duplicate of #110

**Comment by WangSecurity** [comment]
This report will be invalidated based on the escalation on #110.
