### ISSUE TITLE
utsav - DataFeed can return `stale` price because of high `_HEALTHY_DIFF`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-midas-judging#43]
utsav

medium

# DataFeed can return `stale` price because of high `_HEALTHY_DIFF`

## Summary
DataFeed can return `stale` price because of high `_HEALTHY_DIFF`

## Vulnerability Detail
According to chainlink priceFeed, EUR/USD priceFeed has heartbeat of 24 hrs(1 days) but the protocol is using 72 hrs(3 days) which is too high. This can lead to return stale price

[Link of chainlink docs](https://data.chain.link/feeds/ethereum/mainnet/eur-usd)

## Impact
Deposit will use stale price

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L27C30-L27C43

## Tool used
VS code

## Recommendation
Use 24 hrs(1 day) ie recommended by chainlink

Duplicate of #110

**Comment by WangSecurity** [comment]
This report will be invalidated based on the escalation on #110.
