### ISSUE TITLE
KiroBrejka - `_HEALTHY_DIFF` gap is too huge in the `DataFeed` contract

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-midas-judging#61]
KiroBrejka

medium

# `_HEALTHY_DIFF` gap is too huge in the `DataFeed` contract

## Summary
`_HEALTHY_DIFF` gap is too huge, which may lead to stale prices
## Vulnerability Detail
`_HEALTHY_DIFF == 3 days` is unnecessary large period of time, which lead to the oracle returning prices that seem to be fresh but are not 
## Impact
Users  will deposit funds at stale price rate, which is a big problem for big deposits like the minimum starting deposit (100000 euro)
## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L27
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L73-L77
## Tool used

Manual Review

## Recommendation
As the `EUR/USD` price feed have different heartbeats on Arbitrum and on Eth Mainnet, make `_HEALTHY_DIFF` and immutable variable and set it in the `initialize` function as close to the heartbeat as possible(24 hours for Mainnet, 1 hour for Arbitrum)

Duplicate of #110

**Comment by WangSecurity** [comment]
This report will be invalidated based on the escalation on #110.
