### ISSUE TITLE
blutorque - Chainlink refresh check is too long

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-midas-judging#63]
blutorque

medium

# Chainlink refresh check is too long

## Summary
DataFeeds.sol uses the heartbeat to check the freshness of the returned oracle price, however, it is currently sets to `3 days` for the usd feeds, instead of the `1 days`([recommended](https://data.chain.link/feeds/ethereum/mainnet/usdc-usd) by chainlink). 

```solidity
    function _getDataInBase18() private view 
	returns (uint80 roundId, uint256 answer)
    {
        uint8 decimals = aggregator.decimals();
        (uint80 _roundId, int256 _answer, , uint256 updatedAt, ) = aggregator
            .latestRoundData();
        require(_answer > 0, "DF: feed is deprecated");
        require(
>@          block.timestamp - updatedAt <= _HEALTHY_DIFF, 
            "DF: feed is unhealthy"
        );
	...snip...
    }
```
This allow continuous consumption of stale data in `DepositVault` instead of reverting it, 
## Vulnerability Detail
See above. 

## Impact
Usage of stale price.
## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/a4a3cc23bb891913ce44665a4cdea9f5c1190f6c/midas-contracts/contracts/feeds/DataFeed.sol#L27
https://github.com/sherlock-audit/2024-05-midas/blob/a4a3cc23bb891913ce44665a4cdea9f5c1190f6c/midas-contracts/contracts/feeds/DataFeed.sol#L73-L76
## Tool used

Manual Review

## Recommendation
```diff
-    uint256 private constant _HEALTHY_DIFF = 3 days;
+    uint256 private constant _HEALTHY_DIFF = 1 days;
```

*Note: Previously, similar issue has been downgraded to low due to the reason, "heartbeat are adjustable by admin", but here those are hardcoded, cannot be adjusted, see [here](https://github.com/sherlock-audit/2023-12-ubiquity-judging/issues/48#issuecomment-1900024055)*

Duplicate of #110

**Comment by WangSecurity** [comment]
This report will be invalidated based on the escalation on #110.
