### ISSUE TITLE
Josh4324 - Inconsistent Heartbeat Configuration and Potential Data Staleness in Chainlink Feeds

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-midas-judging#72]
Josh4324

high

# Inconsistent Heartbeat Configuration and Potential Data Staleness in Chainlink Feeds

## Summary
Chainlink's data feeds are designed to ensure users receive accurate and up-to-date data. Each feed has a recommended heartbeat interval, which serves as a checkpoint for users to verify the freshness of the data. However, there are inconsistencies and potential issues related to the heartbeat configurations in the DataFeed contract, specifically for the IB01/USD and EUR/USD feeds. 

## Vulnerability Detail
Heartbeat Interval Mismatch for IB01/USD:

The Chainlink documentation recommends a heartbeat interval of 86400 seconds (1 day) for the IB01/USD feed.
https://docs.chain.link/data-feeds/price-feeds/addresses/?network=ethereum&page=1&search=IB01

The DataFeed contract, however, uses a _HEALTHY_DIFF of 3 days for the IB01/USD feed.

The rationale for this 3-day interval is to account for weekends and holidays when the market is closed, as updates are expected only during defined market hours but this will lead to an issue if there is a downtime during market hours for at least 3 days.

Impact on EUR/USD Feed:

The same 3-day _HEALTHY_DIFF is applied to the EUR/USD feed, despite the EUR/USD market not being subject to the same defined market hours as IB01/USD.

This inconsistency means the EUR/USD feed may have unnecessary allowance for data staleness.

## Impact
Delayed Detection of Data Feed Downtime:

The 3-day _HEALTHY_DIFF may result in delayed detection of downtime or issues with the data feed during active market hours for IB01/USD.

Users relying on timely updates might receive outdated or stale data without prompt notification of the issue.

Unnecessary Data Staleness for EUR/USD:

Applying a 3-day _HEALTHY_DIFF to EUR/USD unnecessarily increases the risk of users receiving stale data, as this feed does not operate under the same market hour constraints as IB01/USD.

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L27
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L64-L80

## Tool used

Manual Review

## Recommendation

Align Heartbeat Intervals with Documentation:

Update the DataFeed contract to use the recommended heartbeat interval of 1 day (86400 seconds) for the IB01/USD feed, as specified in the Chainlink documentation.

Customize Heartbeat Intervals for Each Feed:

Ensure that each data feed's heartbeat interval is tailored to its specific market conditions and operational hours.

For EUR/USD, set a more appropriate and shorter _HEALTHY_DIFF interval that reflects the continuous nature of its trading hours.

Monitor and Adjust Intervals Regularly:

Implement regular reviews and adjustments of heartbeat intervals based on market behavior and user feedback to maintain data integrity and accuracy.

Duplicate of #110

**Comment by WangSecurity** [comment]
This report will be invalidated based on the escalation on #110.
