### ISSUE TITLE
blutorque - The `mTBill` tokens involved in illicit activities cannot be burnt,

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-midas-judging#77]
blutorque

medium

# The `mTBill` tokens involved in illicit activities cannot be burnt,

## Summary
See details. 

## Vulnerability Detail
If a user involved in an illicit activities, they are typically blacklisted by the Midas's admin(`BLACKLIST_OPERATOR_ROLE` holder's). The `USDC` assets which are backing the holder's `mTBill` tokens generally get seized under the protocol and the excess `mTBill` tokens are burnt. The `mTBill` tokens are burnt to ensure that the market supply of `mTBill` remains balanced with the actual USDC reserves. 

However, the issue is, the protocol cannot burn the `mTBill` for a `BLACKLISTED_ROLE`, 
https://github.com/sherlock-audit/2024-05-midas/blob/a4a3cc23bb891913ce44665a4cdea9f5c1190f6c/midas-contracts/contracts/mTBILL.sol#L99
```solidity
    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 amount
    )
        internal
        virtual
        override(ERC20PausableUpgradeable)
        onlyNotBlacklisted(from)
>@      onlyNotBlacklisted(to)
    {
        ERC20PausableUpgradeable._beforeTokenTransfer(from, to, amount);
    }
```
This is due to the `burn()` function internally calls the `_beforeTokenTransfer` hook which has `onlyNotBlacklisted` check. 

It's required the protocol admin to first revoke the `BLACKLISTED_ROLE` for that holder, followed by the `burn()` call. But again this brings another risk, where the malicious entity possibly can frontrun the operator `burn()` txn, exchanging the `mTBill` token for another token in the secondary market, before the `burn()` txn takes place. 
## Impact
Since, there would be not enough assets backing the excess `mTBill`, it has direct impact on `mTBill` price economics. 

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/a4a3cc23bb891913ce44665a4cdea9f5c1190f6c/midas-contracts/contracts/mTBILL.sol#L47
## Tool used

Manual Review

## Recommendation
Allow operator to burn `mTBill` tokens for `BLACKLISTED_ROLE` as well, 
```diff
    modifier onlyNotBlacklisted(address account) {
+       if (account == address(0)) return;  
        _onlyNotBlacklisted(account);
        _;
    }
```

Duplicate of #107

**Comment by blutorque** [comment]
The recommend fix is not completely correct, the check should be made in `_beforeTokenTransfer` hook, such as
```solidity
    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 amount
    )
        internal
        virtual
        override(ERC20PausableUpgradeable)
    {
        if(from != address(0) && to==address(0)) return ; 
        
        _onlyNotBlacklisted(from); 
        _onlyNotBlacklisted(to); 
        ERC20PausableUpgradeable._beforeTokenTransfer(from, to, amount);
    }
```

**Comment by blutorque** [comment]
The recommended fix is not completely correct, the check should be made in `_beforeTokenTransfer` hook, such as
```solidity
    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 amount
    )
        internal
        virtual
        override(ERC20PausableUpgradeable)
    {
        if(from != address(0) && to==address(0)) return ; 
        
        _onlyNotBlacklisted(from); 
        _onlyNotBlacklisted(to); 
        ERC20PausableUpgradeable._beforeTokenTransfer(from, to, amount);
    }
```
