### ISSUE TITLE
tpiliposian - Independent Pause Functionality Issue in Vault Contracts

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-midas-judging#83]
tpiliposian

medium

# Independent Pause Functionality Issue in Vault Contracts

## Summary

The `DepositVault.sol` and `RedemptionVault.sol` contracts inherit from a common `Pausable.sol` contract, which allows pausing and unpausing of operations. Although these contracts are designed to have distinct admin roles (`DEPOSIT_VAULT_ADMIN_ROLE` and `REDEMPTION_VAULT_ADMIN_ROLE`), the current implementation of the pause functionality does not allow for independent pausing and unpausing of the `DepositVault` and `RedemptionVault` contracts. This issue could lead to situations where pausing one vault inadvertently affects the other, and vice versa, despite the intended role-based separation.

## Vulnerability Detail

Both `DepositVault` and `RedemptionVault` inherit from the `Pausable` contract, which includes the `pause` and `unpause` functions:
```solidity
abstract contract Pausable is WithMidasAccessControl, PausableUpgradeable {
    modifier onlyPauseAdmin() {
        _onlyRole(pauseAdminRole(), msg.sender);
        _;
    }

    function pause() external onlyPauseAdmin {
        _pause();
    }

    function unpause() external onlyPauseAdmin {
        _unpause();
    }

    function pauseAdminRole() public view virtual returns (bytes32);
}
```
Each vault overrides the `pauseAdminRole()` to return its specific admin role:
```solidity
contract DepositVault is ManageableVault, IDepositVault {
    function pauseAdminRole() public pure override returns (bytes32) {
        return DEPOSIT_VAULT_ADMIN_ROLE;
    }
}

contract RedemptionVault is ManageableVault, IRedemptionVault {
    function pauseAdminRole() public pure override returns (bytes32) {
        return REDEMPTION_VAULT_ADMIN_ROLE;
    }
}
```
The issue arises because the `pause` and `unpause` functions set a global paused state that affects the entire contract. f the `DEPOSIT_VAULT_ADMIN_ROLE` pauses the `DepositVault`, it will also pause any functionality in the `RedemptionVault` that is protected by the `whenNotPaused` modifier. Similarly, if the `REDEMPTION_VAULT_ADMIN_ROLE` unpauses the `RedemptionVault`, it will unpause the `DepositVault` as well.

## Impact

If there is an issue and the deposit role owner pauses the deposits, the redeem function will also be paused. However, if the project decides to unpause the redeem function so users can redeem, calling unpause by the redeem role owner will unpause the whole protocol. This lack of granularity in the pause functionality could lead to security risks and operational inefficiencies.

## Code Snippet

https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/DepositVault.sol#L146-L148

https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/RedemptionVault.sol#L82-L84

https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/access/Pausable.sol#L18-L43

## Tool used

Manual Review

## Recommendation

Implement separate pause flags and modifiers, so the `DepositVault` and `RedemptionVault` can be paused and unpaused independently, ensuring that issues in one vault do not affect the operations of the other.

**Comment by tpiliposian** [comment]
Hey there, I just wanted to comment that this one is not a duplicate of https://github.com/sherlock-audit/2024-05-midas-judging/issues/112

this is not about the roles, this is about independent pause functionality, moreover the 112 is `Won't Fix`, but this one is fixed, how can they be duplicates?

**Comment by tpiliposian** [comment]
Escalate

This is not the dup of #112

The #112 recommends: `Remove the pausability permission for DEPOSIT_VAULT_ADMIN_ROLE and REDEMPTION_VAULT_ADMIN_ROLE.`

But I am not stating that the roles have larger permissions than expected, I am stating that the `unpause` for redemption will `unpause` the depositing as well. So I recommend having independent pausing for depositing and redemption.

**Comment by WangSecurity** [comment]
I agree it's not a duplicate of #112. But, as I understand, the comment [here](https://github.com/sherlock-audit/2024-05-midas-judging/issues/83#issuecomment-2145522579) is correct and indeed when you call pause on one of the vaults, you pause only one vault and it's not a global pause. Am I missing something here?

If not, then planning to de-dupe and invalidate this report.

**Comment by tpiliposian** [comment]
The thing is that there is no pause function in each vault separate, there is `Pausable.sol` and only there are the functions `pause` and `unpause`, so calling the `pause` will set the boolean to true, and all `whenNotPaused` modifiers will work.

**Comment by tpiliposian** [comment]
The thing is that I didn't understand #112 correctly. Now, after reading it again, I believe that yes, the recommendation of that issue will solve this one as well: remove the pausability permission for DEPOSIT_VAULT_ADMIN_ROLE and REDEMPTION_VAULT_ADMIN_ROLE. I meant that if there were different roles for Depositing and Redemption, there should be independent consensuses about them. However, the recommendation in #112 is more accurate—just remove that functionality from them. So, the root case is similar.

**Comment by blutorque** [comment]
> I agree it's not a duplicate of #112. But, as I understand, the comment [here](https://github.com/sherlock-audit/2024-05-midas-judging/issues/83#issuecomment-2145522579) is correct and indeed when you call pause on one of the vaults, you pause only one vault and it's not a global pause. Am I missing something here?
> 
> If not, then planning to de-dupe and invalidate this report.

`DepositVault` and `RedemptionVault` only shares the person who have access to pause the vault. But its required to that person to call `pause()` function separately in both contracts above. So, I think its not a global pause,

**Comment by tpiliposian** [comment]
Yes, you are right. Perhaps I didn't explain it clearly. What I meant to convey is that throughout the whole project, the DEPOSIT_VAULT_ADMIN_ROLE and REDEMPTION_VAULT_ADMIN_ROLE roles are used only for pausing and unpausing; there are no other checks for these roles. That's why I mentioned pausing. However, after rereading #112, I realize that removing the pausing functionality from these roles will solve the issue. Moreover, there is no need for these roles at all, as they do not have any other independent functionality.

**Comment by blutorque** [comment]
Indeed, #112 fix require adding another pausability role, which this finding also mentioned "missing pausing functionality" above,

**Comment by tpiliposian** [comment]
Removing my escalation

**Comment by WangSecurity** [comment]
After looking at the report again, I see it clearly states that the problem is in pausing one vault will also pause the other one, which is incorrect and each of them are paused individually. 

As I’ve said earlier, it’s not a duplicate of #112 and I’m planning to deduplicate it.
