### ISSUE TITLE
valentin2304 - Chainlink's `latestRoundData` might return stale results

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-midas-judging#88]
valentin2304

medium

# Chainlink's `latestRoundData` might return stale results

## Summary
Chainlink's `latestRoundData` might return stale results. The result of `latestRoundData` API is used in `_getDataInBase18()` function, therefore a stale price from Chainlink can lead to loss of funds to end-users.

## Vulnerability Detail
```solidity
function _getDataInBase18()
        private
        view
        returns (uint80 roundId, uint256 answer)
    {
        uint8 decimals = aggregator.decimals();
        (uint80 _roundId, int256 _answer, , uint256 updatedAt, ) = aggregator
            .latestRoundData();
        require(_answer > 0, "DF: feed is deprecated");
        require(
            // solhint-disable-next-line not-rely-on-time
            block.timestamp - updatedAt <= _HEALTHY_DIFF,
            "DF: feed is unhealthy"
        );
        roundId = _roundId;
        answer = uint256(_answer).convertToBase18(decimals);
    }
```
The calls to the `latestRoundData()` function do not validate the output of the Chainlink oracle query. As a result, it is possible to use stale results when returning the price. `latestRoundData()` is able to ensure the round is complete and has returned a valid/expected price by validating additional round data. This is documented in chainlink docs.

## Impact
Medium, stale price from Chainlink can lead to loss of funds to end-users

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L64

## Tool used
Manual Review

## Recommendation
Change the `_getDataInBase18()` function to the following one:
```solidity
function _getDataInBase18()
        private
        view
        returns (uint80 roundId, uint256 answer)
    {
        uint8 decimals = aggregator.decimals();
        (uint80 _roundId, int256 _answer, , uint256 updatedAt, uint80 answeredInRound) = aggregator
            .latestRoundData();
        require(_answer > 0, "DF: feed is deprecated");
        require(answeredInRound >= _roundId, "Stale price"); //this is the missing check for stale price
        require(
            // solhint-disable-next-line not-rely-on-time
            block.timestamp - updatedAt <= _HEALTHY_DIFF,
            "DF: feed is unhealthy"
        );
        roundId = _roundId;
        answer = uint256(_answer).convertToBase18(decimals);
    }
```

**Comment by valentin2304sec** [comment]
I think this report should be marked as a duplicate of #110

**Comment by valentin2304sec** [comment]
Escalate
This is a valid dub of #110 issue

**Comment by sherlock-admin3** [comment]
> Escalate
> This is a valid dub of #110 issue

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xMR0** [comment]
> Escalate This is a valid dub of #110 issue

Invalid issue, such issues are invalid by default at sherlock. Check [here](https://docs.sherlock.xyz/audits/judging/judging)

> Chainlink round completeness check is invalid. The new OCR does not rely on rounds for reporting.

**Comment by WangSecurity** [comment]
The contest's README said that price staleness for less than 3 days is acceptable, but not acceptable if it's 3+ days. I don't see any proof that the price will be stale for more than 3 days. Moreover, round completeness checks are indeed invalid by the rules.

Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [valentin2304sec](https://github.com/sherlock-audit/2024-05-midas-judging/issues/88/#issuecomment-2156240485): rejected
