### ISSUE TITLE
y0ng0p3 - Lack of fallbacks for price feed oracle

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-midas-judging#93]
y0ng0p3

medium

# Lack of fallbacks for price feed oracle

## Summary

The Midas protocol does not implement fallback solutions for price feed oracle. In case Chainlink's aggregators fail to update price data, the protocol will refuse deposits from new users, leading to the protocol's disruption.

## Vulnerability Detail

The protocol uses `DataFeed::_getDataInBase18` function for querying price data of  new users' deposits through [Chainlink's price feed aggregators](https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L70-L71). Nonetheless, if Chainlink's aggregators fail to update the price data, the Midas protocol will not be able to operate. In other words, the function will revert transactions since the received price data become stale (if the last update time exceeds `_HEALTHY_DIFF`).

```solidity
    function _getDataInBase18()
        private
        view
        returns (uint80 roundId, uint256 answer)
    {
        uint8 decimals = aggregator.decimals();
@-->    (uint80 _roundId, int256 _answer, , uint256 updatedAt, ) = aggregator
@-->        .latestRoundData();
        require(_answer > 0, "DF: feed is deprecated");
        require(
            // solhint-disable-next-line not-rely-on-time
@-->        block.timestamp - updatedAt <= _HEALTHY_DIFF,
@-->        "DF: feed is unhealthy"
        );
        roundId = _roundId;
        answer = uint256(_answer).convertToBase18(decimals);
    }
```

[[64-80](https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L64-L80)]

## Impact

Without fallback solutions, the Midas protocol will be unable to operate if Chainlink's aggregators fail to update price data. In this kind kind of scenario, the Midas protocol will be unable to perform new users' deposits, leading to the protocol's disruption.

## Code Snippet

https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L64-L80

## Tool used

Manual Review

## Recommendation

I recommend implementing fallback solutions, such as using other off-chain oracle providers and/or an on-chain oracle like Uniswap's TWAP, for feeding price data in case Chainlink's aggregators fail.

**Comment by y0ng0p3** [comment]
What please makes this issue invalid?
I want to understand. 
@MxAxM

**Comment by MxAxM** [comment]
> What please makes this issue invalid? I want to understand. @MxAxM

It's protocol design choice

**Comment by y0ng0p3** [comment]
Thank you for clarifying.
