### ISSUE TITLE
coffiasd - The heartbeat interval is too large, leading to the use of stale prices

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-midas-judging#96]
coffiasd

medium

# The heartbeat interval is too large, leading to the use of stale prices

## Summary
ChainlinkAdaptor uses constant 3 day heartbeat  when checking if the data feed is fresh.
This is not a reasonable time interval, as prices can update within hours. A too large interval may result in the contract obtaining stale prices.

## Vulnerability Detail
[https://data.chain.link/feeds/ethereum/mainnet/eur-usd](https://data.chain.link/feeds/ethereum/mainnet/eur-usd)
[https://etherscan.io/address/0xb49f677943BC038e9857d61E7d053CaA2C1734C1](https://etherscan.io/address/0xb49f677943BC038e9857d61E7d053CaA2C1734C1)
![](https://raw.githubusercontent.com/coffiasd/images/main/202405311037424.png)

According to the Chainlink documentation and contract, the EUR-USD price can be updated within hours. However, the protocol currently uses a constant interval of 3 days to check for stale prices. This interval is clearly not reasonable and should be adjusted to hours.

## Impact
contract obtaining stale prices

## Code Snippet
https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/feeds/DataFeed.sol#L27

## Tool used

Manual Review

## Recommendation
- adjusted to hours
- add function to change the `_HEALTHY_DIFF`

Duplicate of #110

**Comment by WangSecurity** [comment]
This report will be invalidated based on the escalation on #110.
